name = "medsi-push-worker"
main = "src/index.js"
compatibility_date = "2026-06-16"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[vars]
VAPID_SUBJECT = "mailto:Ori.space.kid@yandex.com"

[[kv_namespaces]]
binding = "PUSH_SUBSCRIPTIONS"
id = "4b2a83b44b7443f0a26c1dbc8ec7adf7"
