(function(){
  if(window.MedsiChatListUI)return;
  const transport=window.MedsiOverlayTransport,phone10=v=>String(v||'').replace(/\D+/g,'').slice(-10),normalize=v=>String(v||'').toLocaleLowerCase('ru-RU').replace(/ё/g,'е').replace(/\s+/g,' ').trim(),sourceBucketByPhone=new Map();
  const ICONS={back:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 5-7 7 7 7"/></svg>',plus:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>',search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="5.8"/><path d="m15 15 4.2 4.2"/></svg>'};
  function listIsVisible(){const screen=document.getElementById('screenChats');return document.body.dataset.screen==='screenChats'&&!!document.querySelector('.educator-exact-clone')&&screen&&!screen.classList.contains('hidden')}
  function installUnifiedTransport(){
    if(!transport||typeof transport.chats!=='function'||transport.__medsiUnifiedChatList)return;transport.__medsiUnifiedChatList=true;
    const baseChats=transport.chats.bind(transport),basePin=typeof transport.pin==='function'?transport.pin.bind(transport):null;
    transport.chats=async function(session,bucket,options){
      if(String(bucket||'')!=='unread'||!listIsVisible())return baseChats(session,bucket,options);
      const [unreadRes,readRes]=await Promise.all([baseChats(session,'unread',options),baseChats(session,'read',options)]),merged=new Map();let order=0;
      const add=(chat,source)=>{if(!chat)return;const phone=phone10(chat.phone);if(!phone||(merged.has(phone)&&source==='read'))return;sourceBucketByPhone.set(phone,source);const copy={...chat,__medsiSourceBucket:source,__medsiOrder:order++};if(source==='read')copy.hasUnread=false;if(copy.pinnedBucket)copy.pinnedBucket='unread';merged.set(phone,copy)};
      (Array.isArray(unreadRes&&unreadRes.chats)?unreadRes.chats:[]).forEach(chat=>add(chat,'unread'));(Array.isArray(readRes&&readRes.chats)?readRes.chats:[]).forEach(chat=>add(chat,'read'));
      const chats=[...merged.values()].sort((a,b)=>Number(!!b.pinnedBucket)-Number(!!a.pinnedBucket)||Number(b.lastTimestamp||0)-Number(a.lastTimestamp||0)||Number(a.__medsiOrder||0)-Number(b.__medsiOrder||0));return {...(unreadRes||{}),chats,medsiUnified:true};
    };
    if(basePin)transport.pin=async function(session,phone,bucket){const source=sourceBucketByPhone.get(phone10(phone));return basePin(session,phone,bucket==='unread'&&source==='read'?'read':bucket)};
  }
  function skeleton(){const wrap=document.createElement('div');wrap.className='medsi-list-skeleton';wrap.setAttribute('aria-label','Загрузка чатов');for(let i=0;i<3;i++){const card=document.createElement('div');card.className='medsi-list-skeleton-card';['title','meta','last'].forEach(cls=>{const line=document.createElement('div');line.className='medsi-list-skeleton-line '+cls;card.appendChild(line)});wrap.appendChild(card)}return wrap}
  function markLegacyBucketSwitches(list){[...list.children].forEach(child=>{const text=String(child.textContent||'');if(text.includes('Вернуться к непрочитанным')||text.includes('Открыть прочитанные чаты'))child.classList.add('medsi-legacy-bucket-switch')})}
  function applyFilter(state){const q=normalize(state.input.value),cards=[...state.list.querySelectorAll(':scope > .chat-card')];let visible=0;cards.forEach(card=>{const show=!q||normalize(card.querySelector('.chat-card-title')?.textContent||'').includes(q);card.classList.toggle('medsi-search-hidden',!show);if(show)visible++});let empty=state.list.querySelector(':scope > .medsi-search-empty');if(q&&cards.length&&!visible){if(!empty){empty=document.createElement('div');empty.className='medsi-search-empty';empty.textContent='Ребёнок не найден.';state.list.appendChild(empty)}}else if(empty)empty.remove()}
  function cascade(state){let index=0;state.list.querySelectorAll(':scope > .chat-card').forEach(card=>{const key=phone10(card.dataset.phone)||card.querySelector('.chat-card-title')?.textContent||'';if(!key||state.seen.has(key))return;state.seen.add(key);card.style.setProperty('--medsi-card-delay',Math.min(index++,8)*26+'ms');card.classList.add('medsi-chat-card-enter');setTimeout(()=>{if(card.isConnected){card.classList.remove('medsi-chat-card-enter');card.style.removeProperty('--medsi-card-delay')}},450)})}
  function polishList(state){const list=state.list;markLegacyBucketSwitches(list);const only=list.children.length===1?list.firstElementChild:null;if(only&&only.classList.contains('chat-empty')&&/^Загрузка/i.test(String(only.textContent||'').trim())){list.replaceChildren(skeleton());return}const empty=list.querySelector(':scope > .chat-empty');if(empty&&(/Новых сообщений нет/i.test(empty.textContent||'')||/Прочитанных чатов нет/i.test(empty.textContent||'')))empty.textContent='Чатов пока нет.';cascade(state);applyFilter(state)}
  function install(){
    installUnifiedTransport();const screen=document.getElementById('screenChats'),list=document.getElementById('chatList'),back=document.getElementById('btnChatsBack'),newChat=document.getElementById('btnNewChat');if(!screen||!list||!back||!newChat)return false;
    const legacyRow=back.parentElement;if(legacyRow)legacyRow.classList.add('medsi-list-legacy-actions');let toolbar=screen.querySelector(':scope > .medsi-chat-list-toolbar'),state=toolbar&&toolbar._medsiState;
    if(!toolbar){toolbar=document.createElement('div');toolbar.className='medsi-chat-list-toolbar';const backProxy=document.createElement('button');backProxy.type='button';backProxy.className='medsi-list-icon-btn medsi-list-back';backProxy.innerHTML=ICONS.back;backProxy.setAttribute('aria-label','Назад');backProxy.title='Назад';backProxy.onclick=()=>back.click();const search=document.createElement('label');search.className='medsi-list-search';search.innerHTML=ICONS.search;const input=document.createElement('input');input.type='search';input.placeholder='Поиск по имени ребёнка';input.autocomplete='off';input.spellcheck=false;input.setAttribute('aria-label','Поиск по имени ребёнка');search.appendChild(input);const newProxy=document.createElement('button');newProxy.type='button';newProxy.className='medsi-list-icon-btn medsi-list-new';newProxy.innerHTML=ICONS.plus;newProxy.setAttribute('aria-label','Написать родителю');newProxy.title='Написать родителю';newProxy.onclick=()=>newChat.click();toolbar.append(backProxy,search,newProxy);screen.insertBefore(toolbar,list);state={list,input,seen:new Set()};toolbar._medsiState=state;input.addEventListener('input',()=>applyFilter(state));new MutationObserver(()=>polishList(state)).observe(list,{childList:true,subtree:false})}
    polishList(state);return true;
  }
  installUnifiedTransport();window.MedsiChatListUI={install};
})();
