(function(){
  const REACTIONS=['❤️','👍','👌','🙏','🥰','😁'];
  const QUICK_REPLIES={
    meetings:`💌 Дорогие родители!\n\n⭐️ Обращаем ваше внимание, что договариваться о встрече с ребенком необходимо напрямую с вашим лечащим врачом!\n\n💬 Пожалуйста, напишите ему и подберите оптимальное время для встречи, с учетом состояния ребенка!\n\n🕐 Расписание встреч с 17:00 до 20:00.\n\n🩵 Спасибо за понимание!\nДетское Отделение Медси`,
    meetTime:`💌 Дорогие родители!\n\n🕐 Время встреч с детьми:\n\nБУДНИ\n🌙 Вечер - 17:00 - 20:00\n\nВЫХОДНЫЕ\n☀️ Утро - 11:00 - 13:00\n🌙 Вечер - 17:00 - 20:00\n\n🙏 Просим приводить в указанное время, так как после встреч у детей начинается прием препаратов и терапия!\n\n🩵 Спасибо за понимание!\nДетское Отделение Медси`,
    calls:`💌 Дорогие родители!\n\n⭐️ Обращаем ваше внимание, что договариваться о звонках ребенку необходимо напрямую с вашим лечащим врачом!\n\n💬 Пожалуйста, напишите ему и подберите оптимальное время для звонка, с учетом состояния ребенка!\n\n🕐 Расписание звонков с 17:00 до 20:00.\n\n🩵 Спасибо за понимание!\nДетское Отделение Медси`,
    therapy:`💌 Дорогие родители!\n\n💊 Обращаем ваше внимание, что по вопросам лечения, процедур, препаратов и другим медицинским вопросам необходимо обращаться напрямую к лечащему врачу. Воспитатели и психологи не располагают такой информацией!\n\n🩵 Спасибо за понимание!\nДетское Отделение Медси`,
    delivery:`💌 Дорогие родители!\n\n🛵 Вы можете привезти или оформить доставку любых продуктов, напитков, еды, одежды и других вещей - в рамках ограничений по безопасности.\n\n🚫 Что запрещено:\n✂️ Канцелярия — ножницы, бумажный нож, точилка, циркуль, железная линейка, канцелярский нож и лезвия.\n💄 Косметика — стеклянные зеркала, щипцы, кусачки, ножницы, пинцеты, острые пилочки, стеклянные флаконы и дезодоранты в металлических аэрозолях.\n🫙 Стеклянная посуда — бутылки, баночки с йогуртом или соком, кружки, тарелки, контейнеры.\n🍴 Столовые приборы — вилки, ложки, ножи. Допустимы только пластиковые ложки.\n🥫 Металлические банки — газировка, соки и другие напитки в жестяных банках.\n⚡️ Кофе и энергетики — нежелательны при медикаментозной терапии и запрещены на этаже.\n🚬 Сигареты - табак, электронные сигареты и т.д.\n💻 Электроника - дети у нас находятся без телефонов, планшетов, компьютеров и наушников. Возможны только простые часы и лампы без острых металлических элементов.\n👕 Одежда — просим передавать одежду без ремней, цепочек, крестиков, металлических подвесок.\n🎨 Творческие наборы — заранее убирайте железные пинцеты, шурупы, гвоздики и прочие металлические детали, идущие в комплекте с аквамозайкой или картиной по номерам.\n🍬 Жевательная резинка — нежелательны при медикаментозной терапии, в связи с тем, что у детей возможна сонливость и они могут уснуть с жвачкой.\n\n✅ Что можно заказать:\n\n🍕 Пиццу, суши, чипсы, газировку, сок, сладости, фрукты и другую еду, которая нравится вашему ребенку, если она не нарушает ограничения по упаковке и безопасности.\n🩳 Одежду, вещи, творческие наборы, канцелярию, книги, раскраски и другие нужные предметы — в рамках описанных выше ограничений.\n💊 Медикаменты по назначению врача — только по предварительной договоренности с лечащим врачом и по назначению.\n💻 Ноутбук или планшет для онлайн-уроков — только для учебы и подключения к онлайн-занятиям.\n\n🩵 Для оформления доставки:\n\nАдрес: Гринвуд с11, Путилково\nКомментарий: доставка на 5 этаж + имя ребёнка.`,
    routine:`💌 Дорогие родители!\n\n🕘 РЕЖИМ ДНЯ\n\n☀️ Утро\n\n8:00 — Подъём\n8:30 — Зарядка\n9:00 — Завтрак\n9:30 — Игры и творчество\n10:00 — Групповая психотерапия\n11:00 — Прогулка\n12:00 — Игры и творчество\n13:00 — Обед\n14:00 — Сон-час\n\n🌙 Вечер\n\n16:00 — Йога / Танцы\n16:30 — Полдник\n17:00 — Игры и творчество\n18:00 — Ужин\n18:15 — Киносеанс\n21:00 — Подготовка ко сну / \nМедицинские процедуры\n22:00 — Отбой\n\n🩵 Спасибо за понимание!\nДетское Отделение Медси`,
    writeTopic:`💌 Дорогие родители!\n\n🗣️ Здесь можно задать вопрос, оставить пожелания по отчётам, получить просьбы ребёнка по доставке и согласовать звонки или онлайн-уроки.\n\n⭐ Вся информация по состоянию ребёнка входит в отчёт и обновляется два раза в день. Ответы на свои вопросы вы получите в составе следующего отчёта!\n\n💊 Все вопросы по медикаментам и терапии обсуждаются с вашим врачом!\n\n💬 Встречи и звонки также обсуждаются с лечащим врачом.\n\n‼️ У воспитателей и психологов нет возможности регулярно отвечать в чате, так как они работают с детьми.\n\n🔔 Расписание отчётов:\n\n☀️ Утро-день — до 16:00\n🌙 День-вечер — до 22:00\n🧠 Психотерапия — до 20:00\n\n🩵 Спасибо за понимание!\nДетское Отделение Медси`
  };
  const DOCTORS={anastasia:`Анастасия Михайловна\n+79253394090`,anna:`Антон Геннадьевич\n+79859927884`,kristina:`Кристина Федоровна\n+79647636887`};
  const threadCache=new Map();
  const text=v=>String(v==null?'':v),phone10=v=>String(v||'').replace(/\D+/g,'').slice(-10),displayPhone=v=>{const p=phone10(v);return p?'8'+p:''};
  const getThread=p=>threadCache.get(phone10(p))||null,setThread=(p,r)=>threadCache.set(phone10(p),{rows:Array.isArray(r)?r:[],at:Date.now()});
  function formatTime(v){const d=new Date(Number(v));return Number.isNaN(d.getTime())?'':d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}
  function preview(c){if(!c)return'';if(c.lastType==='image')return c.lastText||'Фотография';if(c.lastType==='video')return c.lastText||'Видео';return c.lastText||'Нет сообщений'}
  function mediaUrl(m){const id=String(m&&m.fileId||'');if(!id)return'';if(id.startsWith('kv:')||id.startsWith('r2:'))return window.MedsiOverlayTransport.baseUrl+'/media/'+encodeURIComponent(id.slice(3));return'https://drive.google.com/thumbnail?id='+encodeURIComponent(id)+'&sz=w1200'}
  function replyLabel(r){if(!r)return'';if(r.text)return String(r.text).slice(0,120);if(r.type==='image')return'Фотография';if(r.type==='video')return'Видео';return'Сообщение'}

  function mount(overlay,state){
    const transport=window.MedsiOverlayTransport,session=state&&state.session;if(!overlay||!transport||!session||!session.token){if(overlay)overlay.showError('Не удалось получить сессию воспитательского чата.');return}
    overlay.body.replaceChildren();
    const shell=document.createElement('div');shell.className='overlay-educator';
    const sidebar=document.createElement('section');sidebar.className='overlay-chat-list';const head=document.createElement('div');head.className='overlay-chat-list__head';head.innerHTML='<strong>Чат с родителями</strong><span>Непрочитанные сообщения показываются сверху</span>';const list=document.createElement('div');list.className='overlay-chat-list__items';sidebar.append(head,list);
    const panel=document.createElement('section');panel.className='overlay-educator-thread';const header=document.createElement('div');header.className='overlay-educator-thread__header';const back=document.createElement('button');back.type='button';back.className='overlay-educator-thread__back';back.textContent='←';const names=document.createElement('div'),title=document.createElement('strong'),subtitle=document.createElement('span');names.append(title,subtitle);header.append(back,names);const messages=document.createElement('div');messages.className='overlay-thread__messages';const choose=document.createElement('div');choose.className='overlay-thread__empty';choose.textContent='Выберите чат с нужным родителем.';messages.appendChild(choose);
    const replyBar=document.createElement('div');replyBar.className='overlay-reply-bar hidden';const replyText=document.createElement('span'),replyClose=document.createElement('button');replyClose.type='button';replyClose.textContent='×';replyBar.append(replyText,replyClose);const editBar=document.createElement('div');editBar.className='overlay-edit-bar hidden';const editText=document.createElement('span'),editClose=document.createElement('button');editClose.type='button';editClose.textContent='×';editBar.append(editText,editClose);
    const upload=document.createElement('div');upload.className='overlay-upload-preview hidden';const thumb=document.createElement('img');thumb.className='overlay-upload-preview__thumb';const upInfo=document.createElement('div');upInfo.className='overlay-upload-preview__info';const upName=document.createElement('span');upName.className='overlay-upload-preview__name';const upKind=document.createElement('span');upKind.className='overlay-upload-preview__kind';upInfo.append(upName,upKind);const upClose=document.createElement('button');upClose.type='button';upClose.textContent='×';upload.append(thumb,upInfo,upClose);
    const composer=document.createElement('form');composer.className='overlay-composer hidden';const attach=document.createElement('button');attach.type='button';attach.className='overlay-composer__attach';attach.textContent='＋';attach.title='Фото или видео';const quick=document.createElement('button');quick.type='button';quick.className='overlay-composer__quick';quick.textContent='⚡';quick.title='Быстрые ответы';const fileInput=document.createElement('input');fileInput.type='file';fileInput.accept='image/*,video/*';fileInput.hidden=true;const input=document.createElement('textarea');input.className='overlay-composer__input';input.rows=1;input.maxLength=4000;input.placeholder='Сообщение…';const send=document.createElement('button');send.type='submit';send.className='overlay-composer__send';send.textContent='Отправить';composer.append(attach,fileInput,input,send);
    const quickMenu=document.createElement('div');quickMenu.className='overlay-quick-menu hidden';const defs=[['meetings','Встречи с детьми'],['meetTime','Время встреч'],['calls','Звонки детям'],['therapy','Терапия и препараты'],['delivery','Доставка еды и вещей'],['routine','Режим дня'],['writeTopic','Пишите по делу']];defs.forEach(([k,label])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{input.value=QUICK_REPLIES[k];quickMenu.classList.add('hidden');input.focus();input.setSelectionRange(input.value.length,input.value.length)};quickMenu.appendChild(b)});const doctorsBtn=document.createElement('button');doctorsBtn.type='button';doctorsBtn.textContent='Контакты врачей';quickMenu.appendChild(doctorsBtn);const doctorMenu=document.createElement('div');doctorMenu.className='overlay-doctor-menu hidden';[['anastasia','Анастасия Михайловна'],['anna','Антон Геннадьевич'],['kristina','Кристина Федоровна']].forEach(([k,label])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{input.value=DOCTORS[k];quickMenu.classList.add('hidden');doctorMenu.classList.add('hidden');input.focus()};doctorMenu.appendChild(b)});quickMenu.appendChild(doctorMenu);doctorsBtn.onclick=()=>doctorMenu.classList.toggle('hidden');
    panel.append(header,messages,replyBar,editBar,upload,composer,quickMenu);shell.append(sidebar,panel);overlay.body.appendChild(shell);
    const shade=document.createElement('div');shade.className='overlay-context-shade hidden';const menu=document.createElement('div');menu.className='overlay-context-menu hidden';document.body.append(shade,menu);
    let chats=[],active=null,rows=[],sending=false,replyTo=null,editing=null,pendingFile=null,pendingUrl='',disposed=false;
    const closeMenu=()=>{shade.classList.add('hidden');menu.classList.add('hidden');menu.replaceChildren()};shade.onclick=closeMenu;
    function setReply(m){replyTo=m||null;replyBar.classList.toggle('hidden',!replyTo);replyText.textContent=replyTo?'Ответ: '+replyLabel(replyTo):'';if(replyTo){editing=null;editBar.classList.add('hidden');input.focus()}}
    function setEditing(m){editing=m||null;editBar.classList.toggle('hidden',!editing);editText.textContent=editing?'Редактирование сообщения':'';if(editing){replyTo=null;replyBar.classList.add('hidden');input.value=String(editing.text||'');input.focus();input.setSelectionRange(input.value.length,input.value.length)}}
    function clearFile(){pendingFile=null;upload.classList.add('hidden');if(pendingUrl){URL.revokeObjectURL(pendingUrl);pendingUrl=''}thumb.removeAttribute('src')}
    replyClose.onclick=()=>setReply(null);editClose.onclick=()=>{setEditing(null);input.value=''};upClose.onclick=clearFile;
    function action(icon,label,fn,danger){const b=document.createElement('button');b.type='button';b.className='overlay-context-action'+(danger?' danger':'');const i=document.createElement('span');i.className='overlay-context-icon';i.textContent=icon;const t=document.createElement('span');t.textContent=label;b.append(i,t);b.onclick=()=>{closeMenu();fn()};return b}
    function openMenu(m,bubble,e){if(!m||!m.messageKey||String(m.messageKey).startsWith('pending-'))return;e&&e.preventDefault();e&&e.stopPropagation();menu.replaceChildren();const reacts=document.createElement('div');reacts.className='overlay-context-reactions';REACTIONS.forEach(r=>{const b=document.createElement('button');b.type='button';b.textContent=r;b.onclick=async()=>{closeMenu();try{await transport.react(session,m.messageKey,r);refreshThread(true)}catch(err){overlay.showError(err.message)}};reacts.appendChild(b)});menu.appendChild(reacts);const actions=document.createElement('div');actions.className='overlay-context-actions';actions.appendChild(action('↩','Ответить',()=>setReply(m)));if(m.side==='educator'&&m.type==='text')actions.appendChild(action('✎','Редактировать',()=>setEditing(m)));if(m.side==='educator')actions.appendChild(action('⌫','Удалить',async()=>{if(!confirm('Удалить это сообщение?'))return;try{await transport.remove(session,'educator',m.messageKey);refreshThread(true)}catch(err){overlay.showError(err.message)}},true));menu.appendChild(actions);shade.classList.remove('hidden');menu.classList.remove('hidden');if(matchMedia('(max-width:720px)').matches)return;const r=bubble.getBoundingClientRect(),w=310;menu.style.left=Math.min(innerWidth-w-12,Math.max(12,r.left+(r.width-w)/2))+'px';let top=r.bottom+8;if(top+220>innerHeight)top=Math.max(12,r.top-220);menu.style.top=top+'px'}
    function messageNode(m){const own=m&&m.side==='educator',item=document.createElement('article');item.className='overlay-msg '+(own?'overlay-msg--own':'overlay-msg--other');const bubble=document.createElement('div');bubble.className='overlay-msg__bubble';const author=document.createElement('div');author.className='overlay-msg__sender';author.textContent=own?'Воспитатель':'Родитель'+(active&&active.parentName?' '+active.parentName:'');bubble.appendChild(author);if(m&&m.reply){const q=document.createElement('div');q.className='overlay-msg__reply';q.textContent=replyLabel(m.reply);bubble.appendChild(q)}const url=mediaUrl(m);if(url){const wrap=document.createElement('div');wrap.className='overlay-msg__media-wrap';const media=document.createElement(m.type==='video'?'video':'img');media.className='overlay-msg__media';media.src=url;if(m.type==='video'){media.controls=true;media.preload='metadata'}wrap.appendChild(media);bubble.appendChild(wrap)}if(m&&m.text){const body=document.createElement('div');body.className='overlay-msg__text';body.textContent=text(m.text);bubble.appendChild(body)}if(m&&m.reaction){const react=document.createElement('span');react.className='overlay-msg__reaction';react.textContent=m.reaction;bubble.appendChild(react)}const meta=document.createElement('div');meta.className='overlay-msg__meta';meta.textContent=[formatTime(m&&m.timestamp),m&&m.editedAt?'изм.':''].filter(Boolean).join(' · ');bubble.appendChild(meta);bubble.onclick=e=>openMenu(m,bubble,e);bubble.oncontextmenu=e=>openMenu(m,bubble,e);item.appendChild(bubble);return item}
    function renderThread(next,stick=true){rows=Array.isArray(next)?next:[];messages.replaceChildren();if(!rows.length){const n=document.createElement('div');n.className='overlay-thread__empty';n.textContent='Сообщений пока нет.';messages.appendChild(n)}else rows.forEach(r=>messages.appendChild(messageNode(r)));if(stick)requestAnimationFrame(()=>messages.scrollTop=messages.scrollHeight)}
    function merge(unread,read){const map=new Map();(read||[]).forEach(c=>map.set(phone10(c.phone),Object.assign({},c,{hasUnread:false})));(unread||[]).forEach(c=>map.set(phone10(c.phone),Object.assign({},map.get(phone10(c.phone))||{},c,{hasUnread:true})));return Array.from(map.values()).sort((a,b)=>{const ap=a.pinnedBucket?1:0,bp=b.pinnedBucket?1:0;if(ap!==bp)return bp-ap;if(!!a.hasUnread!==!!b.hasUnread)return a.hasUnread?-1:1;return Number(b.lastTimestamp||b.timestamp||0)-Number(a.lastTimestamp||a.timestamp||0)})}
    function cardControl(icon,cls,titleText,fn){const b=document.createElement('button');b.type='button';b.className='overlay-chat-card__control '+cls;b.textContent=icon;b.title=titleText;b.onclick=e=>{e.stopPropagation();fn()};return b}
    function renderList(){list.replaceChildren();if(!chats.length){const n=document.createElement('div');n.className='overlay-chat-list__empty';n.textContent='Чатов пока нет.';list.appendChild(n);return}chats.forEach(c=>{const card=document.createElement('div');card.className='overlay-chat-card'+(c.hasUnread?' unread':'')+(c.pinnedBucket?' pinned':'');card.tabIndex=0;const n=document.createElement('div');n.className='overlay-chat-card__title';n.textContent=c.childName||'Без имени';const meta=document.createElement('div');meta.className='overlay-chat-card__meta';meta.textContent='Родитель: '+(c.parentName||'—')+'\nНомер телефона: '+displayPhone(c.phone);const last=document.createElement('div');last.className='overlay-chat-card__last '+(c.lastSide==='parent'?'parent':'educator');last.textContent=(c.lastSide==='parent'?'Родитель: ':'Вы: ')+preview(c);const controls=document.createElement('div');controls.className='overlay-chat-card__controls';const pin=cardControl('⌖','pin'+(c.pinnedBucket?' active':''),c.pinnedBucket?'Открепить':'Закрепить',async()=>{try{await transport.pin(session,c.phone,c.pinnedBucket?'':(c.hasUnread?'unread':'read'));await loadChats(true)}catch(err){overlay.showError(err.message)}});controls.appendChild(pin);if(c.hasUnread){const eye=cardControl('◉','read','Сделать прочитанным',async()=>{try{await transport.markRead(session,'educator',c.phone);c.hasUnread=false;renderList();loadChats(true)}catch(err){overlay.showError(err.message)}});controls.appendChild(eye)}card.append(n,meta,last,controls);card.onclick=()=>openChat(c);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openChat(c)}};list.appendChild(card)})}
    async function loadChats(silent){if(!silent&&!chats.length){const n=document.createElement('div');n.className='overlay-chat-list__loading';n.textContent='Загрузка...';list.replaceChildren(n)}try{const [u,r]=await Promise.all([transport.chats(session,'unread'),transport.chats(session,'read')]);if(disposed)return;chats=merge(u.chats,r.chats);renderList()}catch(err){if(!silent)overlay.showError((err&&err.message)||'Не удалось загрузить список чатов.')}}
    async function openChat(c){if(!c||!c.phone)return;active=c;shell.classList.add('thread-open');title.textContent=c.childName||'Чат с родителем';subtitle.textContent='Родитель: '+(c.parentName||'—')+' · '+displayPhone(c.phone);composer.classList.remove('hidden');const cached=getThread(c.phone);if(cached)renderThread(cached.rows);else{messages.replaceChildren();const n=document.createElement('div');n.className='overlay-thread__loading';n.textContent='Загрузка...';messages.appendChild(n)}try{const res=await transport.thread(session,c.phone,'',100);if(disposed||!active||phone10(active.phone)!==phone10(c.phone))return;setThread(c.phone,res.messages||[]);renderThread(res.messages||[]);transport.markRead(session,'educator',c.phone).catch(()=>{});c.hasUnread=false;renderList()}catch(err){if(!cached)overlay.showError((err&&err.message)||'Не удалось открыть чат.')}}
    async function refreshThread(preserve){if(!active)return;const gap=messages.scrollHeight-messages.scrollTop-messages.clientHeight;try{const res=await transport.thread(session,active.phone,'',100);if(disposed)return;setThread(active.phone,res.messages||[]);renderThread(res.messages||[],!preserve||gap<80);if(preserve&&gap>80)messages.scrollTop=Math.max(0,messages.scrollHeight-messages.clientHeight-gap)}catch(_){}}
    function setSending(v){sending=!!v;input.disabled=sending;send.disabled=sending;attach.disabled=sending;quick.disabled=sending}
    composer.onsubmit=async e=>{e.preventDefault();if(!active||sending)return;const value=String(input.value||'').trim();if(!value&&!pendingFile)return;setSending(true);try{if(editing){await transport.edit(session,'educator',editing.messageKey,value);setEditing(null);input.value='';await refreshThread(false)}else if(pendingFile){const up=await transport.upload(session,active.phone,pendingFile);await transport.sendMessage(session,'educator',active.phone,{type:up.type||(pendingFile.type.startsWith('video/')?'video':'image'),text:value,fileId:up.fileId,replyToKey:replyTo&&replyTo.messageKey||''});input.value='';setReply(null);clearFile();await refreshThread(false);loadChats(true)}else{const before=rows.slice(),optimistic={side:'educator',type:'text',text:value,timestamp:Date.now(),messageKey:'pending-'+Date.now().toString(36)};renderThread(before.concat(optimistic));input.value='';await transport.sendMessage(session,'educator',active.phone,{type:'text',text:value,replyToKey:replyTo&&replyTo.messageKey||''});setReply(null);setSending(false);refreshThread(false);loadChats(true);return}}catch(err){overlay.showError((err&&err.message)||'Не удалось отправить сообщение.')}finally{setSending(false);input.focus()}};
    attach.onclick=()=>{if(!sending)fileInput.click()};quick.onclick=()=>quickMenu.classList.toggle('hidden');fileInput.onchange=()=>{const f=fileInput.files&&fileInput.files[0];fileInput.value='';if(!f)return;clearFile();pendingFile=f;pendingUrl=URL.createObjectURL(f);thumb.src=pendingUrl;upName.textContent=f.name||'Вложение';upKind.textContent=f.type.startsWith('video/')?'Видео':'Фотография';upload.classList.remove('hidden')};input.onkeydown=e=>{const mobile=matchMedia('(max-width:560px),(hover:none) and (pointer:coarse)').matches;if(!mobile&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}};back.onclick=()=>shell.classList.remove('thread-open');
    loadChats(false);const timer=setInterval(()=>{if(disposed||!overlay.getState())return;loadChats(true);if(active)refreshThread(true)},9000);return()=>{disposed=true;clearInterval(timer);closeMenu();clearFile();shade.remove();menu.remove()}
  }
  window.MedsiEducatorOverlayChat={mount};
})();
