(function(){
const REACTIONS=['❤️','👍','👌','🙏','🥰','😁'];const cache=new Map();
const p10=v=>String(v||'').replace(/\D+/g,'').slice(-10);const phoneDisplay=v=>{const p=p10(v);return p?'8'+p:''};
const fmt=v=>{const d=new Date(Number(v));return Number.isNaN(d.getTime())?'':d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})};
const mediaUrl=m=>{const id=String(m&&m.fileId||'');if(!id)return'';if(id.startsWith('kv:')||id.startsWith('r2:'))return window.MedsiOverlayTransport.baseUrl+'/media/'+encodeURIComponent(id.slice(3));return'https://drive.google.com/thumbnail?id='+encodeURIComponent(id)+'&sz=w1200'};
const replyText=m=>m&&m.text?String(m.text).slice(0,120):m&&m.type==='image'?'Фотография':m&&m.type==='video'?'Видео':'Сообщение';
function mount(overlay,state){const t=window.MedsiOverlayTransport,session=state&&state.session,phone=p10(state&&state.phone);if(!overlay||!t||!session||!session.token||!phone){overlay&&overlay.showError('Не удалось открыть родительский чат.');return}overlay.body.replaceChildren();
const wrap=document.createElement('div');wrap.className='medsi-legacy-wrap parent-role';const card=document.createElement('section');card.className='medsi-legacy-card';
const top=document.createElement('div');top.className='medsi-legacy-top';const back=document.createElement('button');back.className='medsi-legacy-back';back.type='button';back.textContent='←';const chips=document.createElement('div');chips.className='medsi-legacy-chips';const child=document.createElement('span');child.className='medsi-legacy-chip child';child.textContent=state.childName||state.parentName||'Ребёнок';const ph=document.createElement('span');ph.className='medsi-legacy-chip phone';ph.textContent=phoneDisplay(phone);chips.append(child,ph);const spacer=document.createElement('span');top.append(back,chips,spacer);
const note=document.createElement('div');note.className='chat-note';note.innerHTML='<strong>Пожалуйста, пишите только по делу. Воспитатели и психологи работают с детьми и не могут отвечать круглосуточно.</strong><div class="chat-note-list"><span class="chat-note-item">Здесь можно оставить пожелания по отчётам и вопросы. Ответы на них придут в составе следующего отчёта.</span><span class="chat-note-item">Медикаменты, анализы, встречи и звонки согласуются через лечащего врача.</span></div>';
const box=document.createElement('div');box.className='chat-box';
const reply=document.createElement('div');reply.className='chat-reply-preview hidden';reply.innerHTML='<div class="chat-reply-preview-title">Ответ на сообщение</div><div class="chat-reply-preview-text"></div><button class="chat-reply-cancel" type="button">×</button>';
const edit=document.createElement('div');edit.className='chat-edit-preview hidden';edit.innerHTML='<div class="chat-reply-preview-title">Редактирование сообщения</div><div class="chat-reply-preview-text"></div><button class="chat-reply-cancel" type="button">×</button>';
const preview=document.createElement('div');preview.className='chat-image-preview hidden';preview.innerHTML='<div class="preview-item"><img alt="Превью"><button class="preview-remove-btn" type="button">✕</button></div>';
const form=document.createElement('form');form.className='chat-compose';const attach=document.createElement('button');attach.type='button';attach.className='btn chat-attach-btn';attach.textContent='📎';attach.title='Прикрепить фото или видео';const file=document.createElement('input');file.type='file';file.accept='image/*,video/*';file.hidden=true;const input=document.createElement('textarea');input.placeholder='Напишите сообщение…';input.maxLength=4000;const send=document.createElement('button');send.type='submit';send.className='btn btn-teal chat-send-btn';send.textContent='Отправить';form.append(attach,file,input,send);card.append(top,note,box,reply,edit,preview,form);wrap.appendChild(card);overlay.body.appendChild(wrap);
const shade=document.createElement('div');shade.className='chat-context-shade hidden';const menu=document.createElement('div');menu.className='chat-context-menu hidden';document.body.append(shade,menu);
let rows=[],replyTo=null,editing=null,pending=null,previewUrl='',sending=false,dead=false;
function setReply(m){replyTo=m||null;reply.classList.toggle('hidden',!replyTo);reply.querySelector('.chat-reply-preview-text').textContent=replyTo?replyText(replyTo):'';if(replyTo){editing=null;edit.classList.add('hidden');input.focus()}}
function setEdit(m){editing=m||null;edit.classList.toggle('hidden',!editing);edit.querySelector('.chat-reply-preview-text').textContent=editing?String(editing.text||''):'';if(editing){replyTo=null;reply.classList.add('hidden');input.value=String(editing.text||'');input.focus()}}
reply.querySelector('button').onclick=()=>setReply(null);edit.querySelector('button').onclick=()=>{setEdit(null);input.value=''};
function clearFile(){pending=null;preview.classList.add('hidden');if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=''}preview.querySelector('img').removeAttribute('src')}preview.querySelector('button').onclick=clearFile;
function closeMenu(){shade.classList.add('hidden');menu.classList.add('hidden');menu.replaceChildren()}shade.onclick=closeMenu;
function action(icon,label,fn,danger){const b=document.createElement('button');b.type='button';b.className='chat-context-action'+(danger?' danger':'');b.innerHTML='<span class="chat-context-action-icon">'+icon+'</span><span></span>';b.lastChild.textContent=label;b.onclick=()=>{closeMenu();fn()};return b}
function openMenu(m,el,e){if(!m||!m.messageKey||String(m.messageKey).startsWith('pending-'))return;e&&e.preventDefault();e&&e.stopPropagation();menu.replaceChildren();const rs=document.createElement('div');rs.className='chat-context-reactions';REACTIONS.forEach(r=>{const b=document.createElement('button');b.type='button';b.textContent=r;b.onclick=async()=>{closeMenu();try{await t.react(session,m.messageKey,r);refresh(true)}catch(x){overlay.showError(x.message)}};rs.appendChild(b)});menu.appendChild(rs);const acts=document.createElement('div');acts.className='chat-context-actions';acts.appendChild(action('↩','Ответить',()=>setReply(m)));if(m.side==='parent'&&m.type==='text')acts.appendChild(action('✎','Редактировать',()=>setEdit(m)));if(m.side==='parent')acts.appendChild(action('⌫','Удалить',async()=>{if(!confirm('Удалить это сообщение?'))return;try{await t.remove(session,'parent',m.messageKey);refresh(true)}catch(x){overlay.showError(x.message)}},true));menu.appendChild(acts);shade.classList.remove('hidden');menu.classList.remove('hidden');const rect=el.getBoundingClientRect(),w=310;menu.style.left=Math.max(12,Math.min(innerWidth-w-12,rect.left+(rect.width-w)/2))+'px';let y=rect.bottom+8;if(y+220>innerHeight)y=Math.max(12,rect.top-220);menu.style.top=y+'px'}
function node(m){const el=document.createElement('article');el.className='msg '+(m.side==='parent'?'parent':'educator');if(m.side!=='parent'){const a=document.createElement('div');a.className='msg-author';a.textContent='Воспитатель';el.appendChild(a)}if(m.reply){const q=document.createElement('div');q.className='msg-reply-quote';q.textContent=replyText(m.reply);el.appendChild(q)}const u=mediaUrl(m);if(u){const w=document.createElement('div');w.className='msg-image-wrap';const md=document.createElement(m.type==='video'?'video':'img');md.src=u;if(m.type==='video'){md.controls=true;md.preload='metadata'}w.appendChild(md);el.appendChild(w)}if(m.text){const b=document.createElement('div');b.className='msg-body';b.textContent=String(m.text);el.appendChild(b)}if(m.reaction){const r=document.createElement('span');r.className='msg-reaction';r.textContent=m.reaction;el.appendChild(r)}const tm=document.createElement('span');tm.className='msg-time';tm.textContent=[fmt(m.timestamp),m.editedAt?'изм.':''].filter(Boolean).join(' · ');el.appendChild(tm);el.onclick=e=>openMenu(m,el,e);el.oncontextmenu=e=>openMenu(m,el,e);return el}
function render(list,stick=true){rows=Array.isArray(list)?list:[];box.replaceChildren();if(!rows.length){const e=document.createElement('div');e.className='chat-empty';e.textContent='Сообщений пока нет.';box.appendChild(e)}else rows.forEach(m=>box.appendChild(node(m)));if(stick)requestAnimationFrame(()=>box.scrollTop=box.scrollHeight)}
async function refresh(preserve){const gap=box.scrollHeight-box.scrollTop-box.clientHeight;try{const res=await t.thread(session,phone,'',100);if(dead)return;cache.set(phone,{rows:res.messages||[],at:Date.now()});render(res.messages||[],!preserve||gap<80);if(preserve&&gap>80)box.scrollTop=Math.max(0,box.scrollHeight-box.clientHeight-gap);t.markRead(session,'parent',phone).catch(()=>{})}catch(x){if(!rows.length)overlay.showError(x.message||'Не удалось загрузить чат.')}}
const c=cache.get(phone);if(c&&c.rows)render(c.rows);else{box.innerHTML='<div class="chat-empty">Загружаем сообщения…</div>'}refresh(false);
function busy(v){sending=!!v;input.disabled=sending;send.disabled=sending;attach.disabled=sending}
form.onsubmit=async e=>{e.preventDefault();if(sending)return;const value=String(input.value||'').trim();if(!value&&!pending)return;busy(true);try{if(editing){await t.edit(session,'parent',editing.messageKey,value);setEdit(null);input.value='';await refresh(false)}else if(pending){const up=await t.upload(session,phone,pending);await t.sendMessage(session,'parent',phone,{type:up.type||(pending.type.startsWith('video/')?'video':'image'),text:value,fileId:up.fileId,replyToKey:replyTo&&replyTo.messageKey||''});input.value='';setReply(null);clearFile();await refresh(false)}else{const optimistic={side:'parent',type:'text',text:value,timestamp:Date.now(),messageKey:'pending-'+Date.now().toString(36)};const next=rows.concat(optimistic);render(next);input.value='';await t.sendMessage(session,'parent',phone,{type:'text',text:value,replyToKey:replyTo&&replyTo.messageKey||''});setReply(null);busy(false);refresh(false);return}}catch(x){overlay.showError(x.message||'Не удалось отправить сообщение.')}finally{busy(false);input.focus()}};
attach.onclick=()=>file.click();file.onchange=()=>{const f=file.files&&file.files[0];file.value='';if(!f)return;if(!/^image\//i.test(f.type)&&!/^video\//i.test(f.type)){overlay.showError('Можно прикреплять только фото или видео.');return}if(f.size>20*1024*1024){overlay.showError('Размер файла не должен превышать 20 МБ.');return}clearFile();pending=f;previewUrl=URL.createObjectURL(f);preview.querySelector('img').src=previewUrl;preview.classList.remove('hidden')};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};back.onclick=()=>overlay.close();
return()=>{dead=true;closeMenu();shade.remove();menu.remove();if(previewUrl)URL.revokeObjectURL(previewUrl)}}
window.MedsiParentOverlayChat={mount};})();