(function(){
  const REACTIONS=['❤️','👍','👌','🙏','🥰','😁'];
  const threadCache=new Map();
  const key=p=>String(p||'').replace(/\D+/g,'').slice(-10);
  const getCache=p=>threadCache.get(key(p))||null;
  const setCache=(p,rows)=>threadCache.set(key(p),{rows:Array.isArray(rows)?rows:[],at:Date.now()});
  function formatTime(v){const d=new Date(Number(v));return Number.isNaN(d.getTime())?'':d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}
  function mediaUrl(m){const id=String(m&&m.fileId||'');if(!id)return'';if(id.startsWith('kv:')||id.startsWith('r2:'))return window.MedsiOverlayTransport.baseUrl+'/media/'+encodeURIComponent(id.slice(3));return'https://drive.google.com/thumbnail?id='+encodeURIComponent(id)+'&sz=w1200'}
  function replyLabel(r){if(!r)return'';if(r.text)return String(r.text).slice(0,120);if(r.type==='image')return'Фотография';if(r.type==='video')return'Видео';return'Сообщение'}

  function mount(overlay,state){
    const transport=window.MedsiOverlayTransport,phone=String(state&&state.phone||''),session=state&&state.session;
    if(!overlay||!transport||!phone||!session||!session.token){if(overlay)overlay.showError('Не удалось получить данные родительского чата.');return}
    overlay.body.replaceChildren();
    const shell=document.createElement('div');shell.className='overlay-thread overlay-parent-chat';
    const notice=document.createElement('div');notice.className='overlay-parent-notice';
    const noticeTitle=document.createElement('strong');noticeTitle.textContent='Пожалуйста, пишите только по делу. Воспитатели и психологи работают с детьми и не могут отвечать круглосуточно.';
    const noticeList=document.createElement('div');noticeList.className='overlay-parent-notice-list';
    ['Здесь можно оставить пожелания по отчётам и вопросы. Ответы на них придут в составе следующего отчёта.','Медикаменты, анализы, встречи и звонки согласуются через лечащего врача.'].forEach(t=>{const n=document.createElement('span');n.className='overlay-parent-notice-item';n.textContent=t;noticeList.appendChild(n)});notice.append(noticeTitle,noticeList);
    const list=document.createElement('div');list.className='overlay-thread__messages';
    const cached=getCache(phone),cachedRows=cached&&Array.isArray(cached.rows)?cached.rows:[];
    if(!cachedRows.length){const loading=document.createElement('div');loading.className='overlay-thread__loading';loading.textContent='Загружаем сообщения…';list.appendChild(loading)}
    const replyBar=document.createElement('div');replyBar.className='overlay-reply-bar hidden';const replyText=document.createElement('span'),replyClose=document.createElement('button');replyClose.type='button';replyClose.textContent='×';replyBar.append(replyText,replyClose);
    const editBar=document.createElement('div');editBar.className='overlay-edit-bar hidden';const editText=document.createElement('span'),editClose=document.createElement('button');editClose.type='button';editClose.textContent='×';editBar.append(editText,editClose);
    const preview=document.createElement('div');preview.className='overlay-upload-preview hidden';const thumb=document.createElement('img');thumb.className='overlay-upload-preview__thumb';const info=document.createElement('div');info.className='overlay-upload-preview__info';const fileName=document.createElement('span');fileName.className='overlay-upload-preview__name';const fileKind=document.createElement('span');fileKind.className='overlay-upload-preview__kind';info.append(fileName,fileKind);const previewClose=document.createElement('button');previewClose.type='button';previewClose.textContent='×';preview.append(thumb,info,previewClose);
    const composer=document.createElement('form');composer.className='overlay-composer';const attach=document.createElement('button');attach.type='button';attach.className='overlay-composer__attach';attach.textContent='＋';attach.title='Фото или видео';const fileInput=document.createElement('input');fileInput.type='file';fileInput.accept='image/*,video/*';fileInput.hidden=true;const input=document.createElement('textarea');input.className='overlay-composer__input';input.rows=1;input.maxLength=4000;input.placeholder='Сообщение…';const send=document.createElement('button');send.type='submit';send.className='overlay-composer__send';send.textContent='Отправить';composer.append(attach,fileInput,input,send);
    shell.append(notice,list,replyBar,editBar,preview,composer);overlay.body.appendChild(shell);
    const shade=document.createElement('div');shade.className='overlay-context-shade hidden';const menu=document.createElement('div');menu.className='overlay-context-menu hidden';document.body.append(shade,menu);
    let rows=cachedRows.slice(),sending=false,replyTo=null,editing=null,pendingFile=null,pendingUrl='',disposed=false;
    const closeMenu=()=>{shade.classList.add('hidden');menu.classList.add('hidden');menu.replaceChildren()};shade.onclick=closeMenu;
    function setReply(m){replyTo=m||null;replyBar.classList.toggle('hidden',!replyTo);replyText.textContent=replyTo?'Ответ: '+replyLabel(replyTo):'';if(replyTo){editing=null;editBar.classList.add('hidden');input.focus()}}
    function setEditing(m){editing=m||null;editBar.classList.toggle('hidden',!editing);editText.textContent=editing?'Редактирование сообщения':'';if(editing){replyTo=null;replyBar.classList.add('hidden');input.value=String(editing.text||'');input.focus();input.setSelectionRange(input.value.length,input.value.length)}}
    function clearFile(){pendingFile=null;preview.classList.add('hidden');if(pendingUrl){URL.revokeObjectURL(pendingUrl);pendingUrl=''}thumb.removeAttribute('src')}
    replyClose.onclick=()=>setReply(null);editClose.onclick=()=>{setEditing(null);input.value=''};previewClose.onclick=clearFile;
    function action(icon,label,fn,danger){const b=document.createElement('button');b.type='button';b.className='overlay-context-action'+(danger?' danger':'');const i=document.createElement('span');i.className='overlay-context-icon';i.textContent=icon;const t=document.createElement('span');t.textContent=label;b.append(i,t);b.onclick=()=>{closeMenu();fn()};return b}
    function openMenu(m,bubble,e){if(!m||!m.messageKey||String(m.messageKey).startsWith('pending-'))return;e&&e.preventDefault();e&&e.stopPropagation();menu.replaceChildren();const reacts=document.createElement('div');reacts.className='overlay-context-reactions';REACTIONS.forEach(r=>{const b=document.createElement('button');b.type='button';b.textContent=r;b.onclick=async()=>{closeMenu();try{await transport.react(session,m.messageKey,r);refresh(true)}catch(err){overlay.showError(err.message)}};reacts.appendChild(b)});menu.appendChild(reacts);const actions=document.createElement('div');actions.className='overlay-context-actions';actions.appendChild(action('↩','Ответить',()=>setReply(m)));if(m.side==='parent'&&m.type==='text')actions.appendChild(action('✎','Редактировать',()=>setEditing(m)));if(m.side==='parent')actions.appendChild(action('⌫','Удалить',async()=>{if(!confirm('Удалить это сообщение?'))return;try{await transport.remove(session,'parent',m.messageKey);refresh(true)}catch(err){overlay.showError(err.message)}},true));menu.appendChild(actions);shade.classList.remove('hidden');menu.classList.remove('hidden');if(matchMedia('(max-width:720px)').matches)return;const r=bubble.getBoundingClientRect(),w=310;menu.style.left=Math.min(innerWidth-w-12,Math.max(12,r.left+(r.width-w)/2))+'px';let top=r.bottom+8;if(top+220>innerHeight)top=Math.max(12,r.top-220);menu.style.top=top+'px'}
    function node(m){const own=m&&m.side==='parent',item=document.createElement('article');item.className='overlay-msg '+(own?'overlay-msg--own':'overlay-msg--other');const bubble=document.createElement('div');bubble.className='overlay-msg__bubble';const author=document.createElement('div');author.className='overlay-msg__sender';author.textContent=own?'Вы':'Воспитатель';bubble.appendChild(author);if(m&&m.reply){const q=document.createElement('div');q.className='overlay-msg__reply';q.textContent=replyLabel(m.reply);bubble.appendChild(q)}const url=mediaUrl(m);if(url){const wrap=document.createElement('div');wrap.className='overlay-msg__media-wrap';const media=document.createElement(m.type==='video'?'video':'img');media.className='overlay-msg__media';media.src=url;if(m.type==='video'){media.controls=true;media.preload='metadata'}wrap.appendChild(media);bubble.appendChild(wrap)}if(m&&m.text){const body=document.createElement('div');body.className='overlay-msg__text';body.textContent=String(m.text);bubble.appendChild(body)}if(m&&m.reaction){const react=document.createElement('span');react.className='overlay-msg__reaction';react.textContent=m.reaction;bubble.appendChild(react)}const meta=document.createElement('div');meta.className='overlay-msg__meta';meta.textContent=[formatTime(m&&m.timestamp),m&&m.editedAt?'изм.':''].filter(Boolean).join(' · ');bubble.appendChild(meta);bubble.onclick=e=>openMenu(m,bubble,e);bubble.oncontextmenu=e=>openMenu(m,bubble,e);item.appendChild(bubble);return item}
    function render(next,stick=true){rows=Array.isArray(next)?next:[];list.replaceChildren();if(!rows.length){const e=document.createElement('div');e.className='overlay-thread__empty';e.textContent='Сообщений пока нет.';list.appendChild(e)}else rows.forEach(m=>list.appendChild(node(m)));if(stick)requestAnimationFrame(()=>list.scrollTop=list.scrollHeight)}
    if(cachedRows.length)render(cachedRows);
    async function refresh(preserve){const gap=list.scrollHeight-list.scrollTop-list.clientHeight;try{const res=await transport.thread(session,phone,'',100);if(disposed)return;const next=res.messages||[];setCache(phone,next);render(next,!preserve||gap<80);if(preserve&&gap>80)list.scrollTop=Math.max(0,list.scrollHeight-list.clientHeight-gap);transport.markRead(session,'parent',phone).catch(()=>{})}catch(err){if(!rows.length)overlay.showError((err&&err.message)||'Не удалось загрузить чат.')}}
    function setSending(v){sending=!!v;input.disabled=sending;send.disabled=sending;attach.disabled=sending}
    composer.onsubmit=async e=>{e.preventDefault();if(sending)return;const value=String(input.value||'').trim();if(!value&&!pendingFile)return;setSending(true);try{if(editing){await transport.edit(session,'parent',editing.messageKey,value);setEditing(null);input.value='';await refresh(false)}else if(pendingFile){const up=await transport.upload(session,phone,pendingFile);await transport.sendMessage(session,'parent',phone,{type:up.type||(pendingFile.type.startsWith('video/')?'video':'image'),text:value,fileId:up.fileId,replyToKey:replyTo&&replyTo.messageKey||''});input.value='';setReply(null);clearFile();await refresh(false)}else{const optimistic={side:'parent',type:'text',text:value,timestamp:Date.now(),messageKey:'pending-'+Date.now().toString(36)};const before=rows.slice();render(before.concat(optimistic));input.value='';await transport.sendMessage(session,'parent',phone,{type:'text',text:value,replyToKey:replyTo&&replyTo.messageKey||''});setReply(null);setSending(false);refresh(false);return}}catch(err){overlay.showError((err&&err.message)||'Не удалось отправить сообщение.')}finally{setSending(false);input.focus()}};
    attach.onclick=()=>{if(!sending)fileInput.click()};fileInput.onchange=()=>{const f=fileInput.files&&fileInput.files[0];fileInput.value='';if(!f)return;clearFile();pendingFile=f;pendingUrl=URL.createObjectURL(f);thumb.src=pendingUrl;fileName.textContent=f.name||'Вложение';fileKind.textContent=f.type.startsWith('video/')?'Видео':'Фотография';preview.classList.remove('hidden')};input.onkeydown=e=>{const mobile=matchMedia('(max-width:560px),(hover:none) and (pointer:coarse)').matches;if(!mobile&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}};
    refresh(!!cachedRows.length);const timer=setInterval(()=>{if(!disposed&&overlay.getState())refresh(true)},8000);return()=>{disposed=true;clearInterval(timer);closeMenu();clearFile();shade.remove();menu.remove()}
  }
  window.MedsiParentOverlayChat={mount};
})();
