(function(){
  const APP_BASE_URL='https://script.google.com/macros/s/AKfycbzRKRjjI7NoHx8rD5ifEdrcexGuYlMEB453sOC2UTZDeBaybZiNPIY0vDTMkmeHhebVpA/exec';
  const PUSH_SERVICE_URL='https://medsi-push-worker.medsi-children.workers.dev';
  const PHONE_KEY='medsi_parent_phone',LEGACY_PHONE_KEY='medsi_phone',PARENT_KEY='medsi_parent',CHILD_KEY='medsi_child',D1_KEY='medsi_d1_parent_session_v1';
  const $=id=>document.getElementById(id);
  const reportCache={},reportPending={};let currentPhone='',parentName='',childName='',regParentName='',regChildName='',justRegistered=false,d1Session=null,pushReady=false;
  const onlyDigits=v=>String(v||'').replace(/\D+/g,'');const validPhone=v=>onlyDigits(v).length>=10;
  const safeGet=k=>{try{return localStorage.getItem(k)||''}catch(_){return''}};
  const safeSet=(k,v)=>{try{localStorage.setItem(k,v)}catch(_){}};const safeRemove=k=>{try{localStorage.removeItem(k)}catch(_){}};
  function timeout(ms){return new Promise((_,reject)=>setTimeout(()=>reject(new Error('TIMEOUT')),ms))}
  async function callApi(method,args,ms){const run=async()=>{const r=await fetch(APP_BASE_URL,{method:'POST',headers:{'content-type':'text/plain;charset=UTF-8'},body:JSON.stringify({action:'api',method,args:args||[]}),cache:'no-store'});const raw=await r.text();let p;try{p=JSON.parse(raw)}catch(_){throw new Error('Apps Script вернул некорректный ответ.')}if(!r.ok||!p||p.ok!==true)throw new Error((p&&p.message)||('HTTP '+r.status));return p.result};return Promise.race([run(),timeout(ms||15000)])}
  function isStartLike(id){return id==='screenStart'||id==='screenChoose'}
  function initPush(){if(pushReady||!window.MedsiPush)return;pushReady=true;const ph=onlyDigits(safeGet(PHONE_KEY)||safeGet(LEGACY_PHONE_KEY));MedsiPush.init({frameId:'__no_parent_iframe__',appEndpointUrl:APP_BASE_URL,pushServiceUrl:PUSH_SERVICE_URL,identity:validPhone(ph)?{role:'parent',phone:ph}:null})}
  function syncPushIdentity(){if(!window.MedsiPush)return;if(validPhone(currentPhone))MedsiPush.setIdentity({role:'parent',phone:currentPhone});else MedsiPush.clearIdentity()}
  function show(id){['screenStart','screenNames','screenPhoneReg','screenAuth','screenChoose','screenReport','screenSchedule','screenChat'].forEach(x=>$(x).classList.toggle('hidden',x!==id));document.body.dataset.screen=id;$('appCard').classList.toggle('start-mode',id==='screenStart');$('headerBlock').classList.toggle('hidden',isStartLike(id)||id==='screenChat');const el=$(id);el.classList.remove('screen-enter');void el.offsetWidth;el.classList.add('screen-enter');setTimeout(()=>el.classList.remove('screen-enter'),300);setChips();if(window.MedsiPush)MedsiPush.setPanelVisible(id==='screenChoose'||id==='screenChat');window.scrollTo(0,0)}
  function setHeader(title,meta){$('title').textContent=title;$('meta').textContent=meta||''}
  function setChips(){const authed=!!currentPhone&&!['screenStart','screenNames','screenPhoneReg','screenAuth'].some(id=>!$(id).classList.contains('hidden'));const chips=$('chips');chips.classList.toggle('hidden',!authed);chips.style.display=authed?'flex':'none';$('childChip').textContent=childName||'';$('phoneChip').textContent=currentPhone?('8'+onlyDigits(currentPhone).slice(-10)):'';const logout=$('logoutBtn');if(logout)logout.textContent='Выйти'}
  function setBadge(id,visible){const el=$(id);if(!el)return;el.classList.toggle('hidden',!visible);requestAnimationFrame(()=>el.classList.toggle('show',!!visible))}
  function applyUnread(res){const unread=res&&res.reportUnread||{};setBadge('newMsgBanner',!!(res&&res.hasUnread));setBadge('morningReportBadge',!!unread.morning);setBadge('eveningReportBadge',!!unread.evening);setBadge('psychologyReportBadge',!!unread.psychology)}
  function showStart(){setHeader('Медси Бот','Облачная система для просмотра отчётов по вашему ребёнку и для связи с воспитателями.');show('screenStart')}
  function showNames(){setHeader('Регистрация родителя','Укажите данные ребёнка и родителя.');show('screenNames')}
  function showPhoneReg(){setHeader('Телефон для входа','Введите номер, с которым будете входить в систему.');show('screenPhoneReg')}
  function showAuth(){setHeader('Авторизация','Введите номер телефона, который вы указывали при регистрации.');show('screenAuth')}
  function applyBootstrap(res){if(!res||!res.ok)return false;currentPhone=onlyDigits(res.phone||currentPhone);parentName=String(res.parentName||parentName||'').trim();childName=String(res.childName||childName||'').trim();safeSet(PHONE_KEY,currentPhone);safeSet(LEGACY_PHONE_KEY,currentPhone);safeSet(PARENT_KEY,parentName);safeSet(CHILD_KEY,childName);applyUnread(res);syncPushIdentity();return true}
  function showChoose(){if(window.MedsiParentChatScreen)MedsiParentChatScreen.close();setHeader('Медси Бот','Облачная система для просмотра отчётов по вашему ребёнку и для связи с воспитателями.');$('waitNote').classList.toggle('hidden',!justRegistered);show('screenChoose');prewarmAll()}
  function clearSession(){currentPhone='';parentName='';childName='';d1Session=null;safeRemove(PHONE_KEY);safeRemove(LEGACY_PHONE_KEY);safeRemove(PARENT_KEY);safeRemove(CHILD_KEY);safeRemove(D1_KEY);Object.keys(reportCache).forEach(k=>delete reportCache[k]);Object.keys(reportPending).forEach(k=>delete reportPending[k]);if(window.MedsiParentPrewarm)MedsiParentPrewarm.clear();if(window.MedsiParentChatScreen)MedsiParentChatScreen.close();syncPushIdentity()}
  async function restoreSaved(){
    const ph=onlyDigits(safeGet(PHONE_KEY)||safeGet(LEGACY_PHONE_KEY));
    if(!validPhone(ph)){showStart();return}
    currentPhone=ph;
    parentName=String(safeGet(PARENT_KEY)||'').trim();
    childName=String(safeGet(CHILD_KEY)||'').trim();
    syncPushIdentity();
    showChoose();
    try{
      const res=await callApi('getParentBootstrap',[ph],12000);
      if(!applyBootstrap(res)){clearSession();showStart();return}
      setChips();
      prewarmAll();
    }catch(_){
      // A temporary network failure must not kick an already saved parent out.
      // The visible menu stays available and background prewarm can recover later.
    }
  }
  function isSingleWord(v){return !/\s/.test(String(v||'').trim())}
  async function register(){const digits=onlyDigits($('phoneInputReg').value);const err=$('phoneErrorReg'),info=$('alreadyRegistered'),btn=$('registerBtn');err.classList.add('hidden');info.classList.add('hidden');if(!validPhone(digits)){err.textContent='Введите номер — минимум 10 цифр.';err.classList.remove('hidden');return}btn.disabled=true;try{const res=await callApi('registerParent',[regParentName,regChildName,digits],20000);if(!res||!res.ok)throw new Error((res&&res.message)||'Не удалось выполнить регистрацию.');if(res.duplicate){info.textContent='Похоже, вы уже зарегистрированы в системе. Пожалуйста, используйте кнопку «Авторизация», чтобы войти и посмотреть отчёты.';info.classList.remove('hidden');justRegistered=false;return}currentPhone=digits;parentName=regParentName;childName=regChildName;justRegistered=true;safeSet(PHONE_KEY,currentPhone);safeSet(LEGACY_PHONE_KEY,currentPhone);safeSet(PARENT_KEY,parentName);safeSet(CHILD_KEY,childName);syncPushIdentity();prewarmAll();showChoose();callApi('getParentBootstrap',[currentPhone],12000).then(r=>{applyBootstrap(r);setChips();prewarmAll()}).catch(()=>{})}catch(e){err.textContent=String(e&&e.message||e)==='TIMEOUT'?'Сервер долго не отвечает. Попробуйте ещё раз.':String(e&&e.message||e);err.classList.remove('hidden')}finally{btn.disabled=false}}
  async function auth(){const digits=onlyDigits($('phoneInputAuth').value);const err=$('phoneErrorAuth'),btn=$('authBtn');err.classList.add('hidden');if(!validPhone(digits)){err.textContent='Введите номер — минимум 10 цифр.';err.classList.remove('hidden');return}btn.disabled=true;try{const res=await callApi('getParentBootstrap',[digits],15000);if(!res||!res.ok){err.textContent='Ваш номер не найден в системе. Если вы поступаете повторно, пожалуйста, нажмите «Назад» и пройдите регистрацию еще раз!';err.classList.remove('hidden');return}currentPhone=digits;justRegistered=false;applyBootstrap(res);prewarmAll();showChoose()}catch(e){err.textContent=String(e&&e.message||e)==='TIMEOUT'?'Сервер долго не отвечает. Попробуйте ещё раз.':'Сервер недоступен.';err.classList.remove('hidden')}finally{btn.disabled=false}}
  function extractSession(res){if(res&&res.token)return res;if(res&&res.session&&res.session.token)return res.session;return null}
  function saveD1Session(session){if(!session||!session.token)return null;d1Session=session;safeSet(D1_KEY,JSON.stringify({phone:onlyDigits(currentPhone).slice(-10),session}));return session}
  async function warmD1(){if(!currentPhone)return null;try{const saved=JSON.parse(safeGet(D1_KEY)||'null');const s=extractSession(saved);const phone=onlyDigits(saved&&saved.phone||currentPhone).slice(-10);if(s&&Number(s.expiresAt||0)>Date.now()+30000&&phone===onlyDigits(currentPhone).slice(-10))return saveD1Session(s)}catch(_){}try{const res=await callApi('getD1ChatSession',['parent',currentPhone,''],10000);const s=extractSession(res);return s?saveD1Session(s):null}catch(_){return null}}
  function warmReport(kind){if(reportCache[kind])return Promise.resolve(reportCache[kind]);if(reportPending[kind])return reportPending[kind];if(!currentPhone)return Promise.resolve(null);const phone=currentPhone;const p=(kind==='psychology'?callApi('getPsychologyReportFor',[phone],15000):callApi('getReportFor',[phone,kind],15000)).then(res=>{if(res&&res.ok&&onlyDigits(currentPhone).slice(-10)===onlyDigits(phone).slice(-10))reportCache[kind]=res;return res}).catch(()=>null).finally(()=>{if(reportPending[kind]===p)delete reportPending[kind]});reportPending[kind]=p;return p}
  function prewarmAll(){if(!currentPhone)return;warmD1().then(session=>{if(session&&window.MedsiParentPrewarm)MedsiParentPrewarm.warm(session,currentPhone)});warmReport('morning');warmReport('evening');warmReport('psychology')}
  function reportTitle(kind){return kind==='morning'?'Утренний отчёт':kind==='evening'?'Вечерний отчёт':'Групповая психотерапия'}
  function normalizeBlock(v){return String(v||'').replace(/\s+/g,' ').trim()}
  function dedupeExactReport(text){const raw=String(text||'').trim();if(!raw)return raw;const blocks=raw.split(/\n\s*\n+/).map(x=>x.trim()).filter(Boolean);if(blocks.length>1){const seen=new Set(),unique=[];for(const block of blocks){const key=normalizeBlock(block);if(!key||seen.has(key))continue;seen.add(key);unique.push(block)}if(unique.length<blocks.length)return unique.join('\n\n')}const lines=raw.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(lines.length===2&&normalizeBlock(lines[0])===normalizeBlock(lines[1]))return lines[0];return raw}
  function hideReportBadge(kind){setBadge(kind==='morning'?'morningReportBadge':kind==='evening'?'eveningReportBadge':'psychologyReportBadge',false)}
  async function openReport(kind){setHeader(reportTitle(kind),'');$('reportDisclaimer').classList.toggle('hidden',kind==='psychology');$('reportContent').innerHTML='<div class="report-loading"><span class="report-loading-spinner"></span><span>Загружаем...</span></div>';$('reportError').classList.add('hidden');show('screenReport');hideReportBadge(kind);let res=reportCache[kind];if(!res)res=await warmReport(kind);if(!res||!res.ok){$('reportError').textContent=(res&&res.message)||'Отчёт пока недоступен.';$('reportError').classList.remove('hidden');$('reportContent').textContent='';return}$('reportContent').textContent=dedupeExactReport(res.text||'Отчёта пока нет. Пожалуйста, попробуйте позже 🙏')}
  function showSchedule(){setHeader('Режим дня','Расписание детского отделения.');show('screenSchedule')}
  async function openChat(){try{const session=d1Session||await warmD1();if(!session)throw new Error('Не удалось получить доступ к чату.');if(!window.MedsiParentChatScreen)throw new Error('Чат не загрузился.');setBadge('newMsgBanner',false);show('screenChat');await MedsiParentChatScreen.open({session,phone:currentPhone,parentName,childName,onBack:showChoose})}catch(e){alert(String(e&&e.message||e))}}

  $('btnGoRegister').onclick=()=>showNames();$('btnGoAuth').onclick=()=>showAuth();$('startHelpBtn').onclick=()=>{const p=$('startHelpPanel'),open=p.classList.toggle('is-open');p.setAttribute('aria-hidden',open?'false':'true')};
  $('namesBackBtn').onclick=showStart;$('namesAuthBtn').onclick=showAuth;$('phoneRegBackBtn').onclick=showNames;$('authBackBtn').onclick=showStart;
  $('toPhoneReg').onclick=()=>{const pFirst=$('parentFirst').value.trim(),pLast=$('parentLast').value.trim(),cFirst=$('childFirst').value.trim(),cLast=$('childLast').value.trim(),err=$('namesError');if(!pFirst||!cFirst){err.textContent='Введите имя родителя и имя ребёнка.';err.classList.remove('hidden');return}if(!cLast&&!pLast){err.textContent='Введите фамилию ребёнка или фамилию родителя.';err.classList.remove('hidden');return}if(![pFirst,pLast,cFirst,cLast].filter(Boolean).every(isSingleWord)){err.textContent='В каждое поле вводите только имя или фамилию, без отчества.';err.classList.remove('hidden');return}err.classList.add('hidden');regParentName=[pFirst,pLast].filter(Boolean).join(' ');regChildName=[cFirst,cLast].filter(Boolean).join(' ');showPhoneReg()};
  $('registerBtn').onclick=register;$('authBtn').onclick=auth;$('btnChat').onclick=openChat;$('btnMorning').onclick=()=>openReport('morning');$('btnEvening').onclick=()=>openReport('evening');$('btnPsychology').onclick=()=>openReport('psychology');$('btnSchedule').onclick=showSchedule;
  ['reportBackBtn','scheduleBackBtn'].forEach(id=>$(id).onclick=showChoose);$('logoutBtn').onclick=()=>{clearSession();justRegistered=false;showStart()};
  ['phoneInputReg','phoneInputAuth'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')(id==='phoneInputReg'?register:auth)()}));
  initPush();restoreSaved();
})();