(function(){
  const APP_BASE_URL='https://script.google.com/macros/s/AKfycbzRKRjjI7NoHx8rD5ifEdrcexGuYlMEB453sOC2UTZDeBaybZiNPIY0vDTMkmeHhebVpA/exec';
  const PUSH_SERVICE_URL='https://medsi-push-worker.medsi-children.workers.dev';
  const PHONE_KEY='medsi_parent_phone',LEGACY_PHONE_KEY='medsi_phone',PARENT_KEY='medsi_parent',CHILD_KEY='medsi_child',PARENT_SESSION_KEY='medsi_parent_auth_session_v1',D1_KEY='medsi_d1_parent_session_v1',REG_ATTEMPT_KEY='medsi_parent_registration_attempt_v1',REAUTH_KEY='medsi_parent_reauthorization_v1';
  const $=id=>document.getElementById(id);
  const reportCache={},reportPending={};let currentPhone='',parentName='',childName='',regParentName='',regChildName='',justRegistered=false,d1Session=null,pushReady=false,parentSession='',flowRun=0,currentReportKind='morning',currentReportText='',historyModalText='';
  const onlyDigits=v=>String(v||'').replace(/\D+/g,'');const validPhone=v=>onlyDigits(v).length>=10;
  const safeGet=k=>{try{return localStorage.getItem(k)||''}catch(_){return''}};
  const safeSet=(k,v)=>{try{localStorage.setItem(k,v)}catch(_){}};const safeRemove=k=>{try{localStorage.removeItem(k)}catch(_){}};
  function timeout(ms){return new Promise((_,reject)=>setTimeout(()=>reject(new Error('TIMEOUT')),ms))}
  async function callApi(method,args,ms){const run=async()=>{const r=await fetch(APP_BASE_URL,{method:'POST',headers:{'content-type':'text/plain;charset=UTF-8'},body:JSON.stringify({action:'api',method,args:args||[]}),cache:'no-store'});const raw=await r.text();let p;try{p=JSON.parse(raw)}catch(_){throw new Error('Apps Script вернул некорректный ответ.')}if(!r.ok||!p||p.ok!==true)throw new Error((p&&p.message)||('HTTP '+r.status));return p.result};return Promise.race([run(),timeout(ms||15000)])}
  function isStartLike(id){return id==='screenStart'||id==='screenChoose'}
  function initPush(){if(pushReady||!window.MedsiPush)return;pushReady=true;const ph=onlyDigits(safeGet(PHONE_KEY)||safeGet(LEGACY_PHONE_KEY));MedsiPush.init({frameId:'__no_parent_iframe__',appEndpointUrl:APP_BASE_URL,pushServiceUrl:PUSH_SERVICE_URL,identity:validPhone(ph)?{role:'parent',phone:ph}:null})}
  function syncPushIdentity(){if(!window.MedsiPush)return;if(validPhone(currentPhone))MedsiPush.setIdentity({role:'parent',phone:currentPhone,parentSession:parentSession||''});else MedsiPush.clearIdentity()}
  function show(id){['screenStart','screenNames','screenPhoneReg','screenAuth','screenRegistrationPending','screenAuthPending','screenChoose','screenReport','screenReportHistory','screenSchedule','screenChat'].forEach(x=>$(x).classList.toggle('hidden',x!==id));document.body.dataset.screen=id;$('appCard').classList.toggle('start-mode',id==='screenStart');$('headerBlock').classList.toggle('hidden',isStartLike(id)||id==='screenChat'||id==='screenRegistrationPending'||id==='screenAuthPending');const el=$(id);el.classList.remove('screen-enter');void el.offsetWidth;el.classList.add('screen-enter');setTimeout(()=>el.classList.remove('screen-enter'),300);setChips();if(window.MedsiPush)MedsiPush.setPanelVisible(id==='screenChoose'||id==='screenChat');window.scrollTo(0,0)}
  function setHeader(title,meta){$('title').textContent=title;$('meta').textContent=meta||''}
  function setChips(){const authed=!!currentPhone&&!!parentSession&&!['screenStart','screenNames','screenPhoneReg','screenAuth','screenRegistrationPending','screenAuthPending'].some(id=>!$(id).classList.contains('hidden'));const chips=$('chips');chips.classList.toggle('hidden',!authed);chips.style.display=authed?'flex':'none';$('childChip').textContent=childName||'';$('phoneChip').textContent=currentPhone?('8'+onlyDigits(currentPhone).slice(-10)):'';const logout=$('logoutBtn');if(logout)logout.textContent='Выйти'}
  function setBadge(id,visible){const el=$(id);if(!el)return;el.classList.toggle('hidden',!visible);requestAnimationFrame(()=>el.classList.toggle('show',!!visible))}
  function applyUnread(res){const unread=res&&res.reportUnread||{};setBadge('newMsgBanner',!!(res&&res.hasUnread));setBadge('morningReportBadge',!!unread.morning);setBadge('eveningReportBadge',!!unread.evening);setBadge('psychologyReportBadge',!!unread.psychology)}
  function showStart(){setHeader('Медси Бот','Облачная система для просмотра отчётов по вашему ребёнку и для связи с воспитателями.');show('screenStart')}
  function showNames(){setHeader('Регистрация родителя','Укажите данные ребёнка и родителя.');show('screenNames')}
  function showPhoneReg(){setHeader('Телефон для входа','Введите номер, с которым будете входить в систему.');show('screenPhoneReg')}
  function showAuth(){setHeader('Авторизация','Введите номер телефона, который вы указывали при регистрации.');show('screenAuth')}
  function applyBootstrap(res){if(!res||!res.ok||!res.parentSession)return false;currentPhone=onlyDigits(res.phone||currentPhone);parentName=String(res.parentName||parentName||'').trim();childName=String(res.childName||childName||'').trim();parentSession=String(res.parentSession);safeSet(PARENT_SESSION_KEY,parentSession);safeSet(PHONE_KEY,currentPhone);safeSet(LEGACY_PHONE_KEY,currentPhone);safeSet(PARENT_KEY,parentName);safeSet(CHILD_KEY,childName);applyUnread(res);syncPushIdentity();return true}
  function showChoose(){if(window.MedsiParentChatScreen)MedsiParentChatScreen.close();setHeader('Медси Бот','Облачная система для просмотра отчётов по вашему ребёнку и для связи с воспитателями.');$('waitNote').classList.toggle('hidden',!justRegistered);show('screenChoose');prewarmAll()}
  function clearSession(){currentPhone='';parentName='';childName='';parentSession='';d1Session=null;flowRun++;safeRemove(PHONE_KEY);safeRemove(LEGACY_PHONE_KEY);safeRemove(PARENT_KEY);safeRemove(CHILD_KEY);safeRemove(PARENT_SESSION_KEY);safeRemove(D1_KEY);Object.keys(reportCache).forEach(k=>delete reportCache[k]);Object.keys(reportPending).forEach(k=>delete reportPending[k]);if(window.MedsiParentPrewarm)MedsiParentPrewarm.clear();if(window.MedsiParentChatScreen)MedsiParentChatScreen.close();syncPushIdentity()}
  async function restoreSaved(){
    const ph=onlyDigits(safeGet(PHONE_KEY)||safeGet(LEGACY_PHONE_KEY));
    if(!validPhone(ph)){showStart();return}
    currentPhone=ph;
    parentName=String(safeGet(PARENT_KEY)||'').trim();
    childName=String(safeGet(CHILD_KEY)||'').trim();
    parentSession=safeGet(PARENT_SESSION_KEY);if(!parentSession){clearSession();$('phoneInputAuth').value=ph;showAuth();return}syncPushIdentity();
    showChoose();
    try{
      const res=await callApi('getParentBootstrap',[ph,parentSession],12000);
      if(!applyBootstrap(res)){clearSession();$('phoneInputAuth').value=ph;showAuth();return}
      setChips();
      prewarmAll();
    }catch(_){
      // A temporary network failure must not kick an already saved parent out.
      // The visible menu stays available and background prewarm can recover later.
    }
  }
  function isSingleWord(v){return !/\s/.test(String(v||'').trim())}
  const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  function readJson(key){try{return JSON.parse(safeGet(key)||'null')}catch(_){return null}}
  function makeFlowId(prefix){let value='';try{if(crypto&&crypto.randomUUID)value=crypto.randomUUID()}catch(_){}if(!value)value=Date.now().toString(36)+'_'+Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2);return prefix+'_'+value.replace(/[^A-Za-z0-9_-]/g,'')}
  function registrationFingerprint(data){return [onlyDigits(data.phone).slice(-10),data.parentName,data.childName].join('|')}
  function finishRegistration(res){if(!applyBootstrap(res))throw new Error('Регистрация завершена, но сессия не получена. Продолжаем проверку.');safeRemove(REG_ATTEMPT_KEY);justRegistered=true;showChoose();prewarmAll()}
  async function runRegistrationFlow(data){const run=++flowRun;show('screenRegistrationPending');$('registrationPendingText').textContent='Пожалуйста, подождите. Мы сохраняем данные и готовим Медси Бот.';let delay=2200;while(run===flowRun){try{let res=await callApi('registerParent',[data.parentName,data.childName,data.phone,data.attemptId],20000);if(run!==flowRun)return;if(res&&res.duplicate){safeRemove(REG_ATTEMPT_KEY);$('phoneInputAuth').value=data.phone;await beginReauthorization(data.phone);return}if(res&&res.ok&&res.parentSession){finishRegistration(res);return}res=await callApi('getParentRegistrationStatus',[data.phone,data.attemptId],12000);if(run!==flowRun)return;if(res&&res.ok&&res.parentSession){finishRegistration(res);return}}catch(e){if(run!==flowRun)return;$('registrationPendingText').textContent='Регистрация занимает больше времени, чем обычно. Проверяем результат…'}await wait(delay);delay=Math.min(8000,delay+1200)}}
  async function register(){const digits=onlyDigits($('phoneInputReg').value),err=$('phoneErrorReg'),info=$('alreadyRegistered');err.classList.add('hidden');info.classList.add('hidden');if(!validPhone(digits)){err.textContent='Введите номер — минимум 10 цифр.';err.classList.remove('hidden');return}const snapshot={phone:digits,parentName:regParentName,childName:regChildName};const saved=readJson(REG_ATTEMPT_KEY);snapshot.attemptId=saved&&saved.fingerprint===registrationFingerprint(snapshot)?saved.attemptId:makeFlowId('reg');snapshot.fingerprint=registrationFingerprint(snapshot);safeSet(REG_ATTEMPT_KEY,JSON.stringify(snapshot));runRegistrationFlow(snapshot)}
  function resetAuthPendingUi(){const screen=$('screenAuthPending');screen.classList.remove('is-approved');$('authPendingSpinner').classList.remove('hidden');$('authApprovedIcon').classList.add('hidden');$('authPendingTitle').textContent='Авторизация начата';$('authPendingText').textContent='Пожалуйста, подождите, пока воспитатель подтвердит вход.';$('authRequestCodeWrap').classList.remove('hidden');$('authPendingBackBtn').classList.add('hidden')}
  function showAuthApproved(res){if(!applyBootstrap(res))throw new Error('Не удалось сохранить подтверждённый вход.');safeRemove(REAUTH_KEY);const screen=$('screenAuthPending');screen.classList.add('is-approved');$('authPendingSpinner').classList.add('hidden');$('authApprovedIcon').classList.remove('hidden');$('authRequestCodeWrap').classList.add('hidden');$('authPendingTitle').textContent='Авторизация подтверждена!';$('authPendingText').textContent='Вход сохранён на этом устройстве.';setTimeout(()=>{if(document.body.dataset.screen==='screenAuthPending'){justRegistered=false;showChoose();prewarmAll()}},1800)}
  function showAuthStopped(status,message){$('authPendingSpinner').classList.add('hidden');$('authRequestCodeWrap').classList.add('hidden');$('authPendingTitle').textContent=status==='DENIED'?'Авторизация отклонена':status==='NOT_FOUND'?'Номер не найден':'Срок запроса истёк';$('authPendingText').textContent=message||'Вы можете отправить новый запрос.';$('authPendingBackBtn').classList.remove('hidden')}
  async function runReauthorizationFlow(data,createFirst){const run=++flowRun;resetAuthPendingUi();show('screenAuthPending');let shouldCreate=!!createFirst;while(run===flowRun){try{const res=shouldCreate?await callApi('requestParentReauthorization',[data.phone,data.requestId],18000):await callApi('getParentReauthorizationStatus',[data.phone,data.requestId],12000);if(run!==flowRun)return;if(res&&res.code==='NOT_FOUND'&&res.ok===false){safeRemove(REAUTH_KEY);showAuthStopped('NOT_FOUND',res.message||'Этот номер не найден среди активных родителей.');return}shouldCreate=false;if(!res||res.ok===false)throw new Error((res&&res.message)||'Не удалось проверить авторизацию.');if(res.code)$('authRequestCode').textContent=res.code;if(res.parentSession||res.status==='APPROVED'){showAuthApproved(res);return}if(res.status==='DENIED'){safeRemove(REAUTH_KEY);showAuthStopped('DENIED','Воспитатель отклонил запрос. При необходимости свяжитесь с отделением.');return}if(res.status==='EXPIRED'){safeRemove(REAUTH_KEY);showAuthStopped('EXPIRED','Запрос больше не действует. Отправьте новый запрос на вход.');return}if(res.status==='NOT_FOUND')shouldCreate=true}catch(e){if(run!==flowRun)return;$('authPendingText').textContent='Связь временно прервана. Продолжаем проверять запрос…'}await wait(5000)}}
  async function beginReauthorization(phoneRaw){const digits=onlyDigits(phoneRaw);if(!validPhone(digits))return;let saved=readJson(REAUTH_KEY);if(!saved||onlyDigits(saved.phone).slice(-10)!==digits.slice(-10))saved={phone:digits,requestId:makeFlowId('auth')};safeSet(REAUTH_KEY,JSON.stringify(saved));runReauthorizationFlow(saved,true)}
  async function auth(){const digits=onlyDigits($('phoneInputAuth').value),err=$('phoneErrorAuth');err.classList.add('hidden');if(!validPhone(digits)){err.textContent='Введите номер — минимум 10 цифр.';err.classList.remove('hidden');return}beginReauthorization(digits)}
  function extractSession(res){if(res&&res.token)return res;if(res&&res.session&&res.session.token)return res.session;return null}
  function saveD1Session(session){if(!session||!session.token)return null;d1Session=session;safeSet(D1_KEY,JSON.stringify({phone:onlyDigits(currentPhone).slice(-10),session}));return session}
  async function warmD1(){if(!currentPhone)return null;try{const saved=JSON.parse(safeGet(D1_KEY)||'null');const s=extractSession(saved);const phone=onlyDigits(saved&&saved.phone||currentPhone).slice(-10);if(s&&Number(s.expiresAt||0)>Date.now()+30000&&phone===onlyDigits(currentPhone).slice(-10))return saveD1Session(s)}catch(_){}try{const res=await callApi('getD1ChatSession',['parent',currentPhone,parentSession],10000);const s=extractSession(res);return s?saveD1Session(s):null}catch(_){return null}}
  function warmReport(kind,fresh){if(!fresh&&reportCache[kind])return Promise.resolve(reportCache[kind]);if(!fresh&&reportPending[kind])return reportPending[kind];if(!currentPhone)return Promise.resolve(null);const phone=currentPhone;const p=(kind==='psychology'?callApi('getPsychologyReportFor',[phone,parentSession],15000):callApi('getReportFor',[phone,kind,parentSession],15000)).then(res=>{if(res&&res.ok&&onlyDigits(currentPhone).slice(-10)===onlyDigits(phone).slice(-10))reportCache[kind]=res;return res}).catch(()=>null).finally(()=>{if(reportPending[kind]===p)delete reportPending[kind]});reportPending[kind]=p;return p}
  function prewarmAll(){if(!currentPhone)return;warmD1().then(session=>{if(session&&window.MedsiParentPrewarm)MedsiParentPrewarm.warm(session,currentPhone)});warmReport('morning');warmReport('evening');warmReport('psychology')}
  function reportTitle(kind){return kind==='morning'?'Утренний отчёт':kind==='evening'?'Вечерний отчёт':'Групповая психотерапия'}
  function normalizeBlock(v){return String(v||'').replace(/\s+/g,' ').trim()}
  function dedupeExactReport(text){const raw=String(text||'').trim();if(!raw)return raw;const blocks=raw.split(/\n\s*\n+/).map(x=>x.trim()).filter(Boolean);if(blocks.length>1){const seen=new Set(),unique=[];for(const block of blocks){const key=normalizeBlock(block);if(!key||seen.has(key))continue;seen.add(key);unique.push(block)}if(unique.length<blocks.length)return unique.join('\n\n')}const lines=raw.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(lines.length===2&&normalizeBlock(lines[0])===normalizeBlock(lines[1]))return lines[0];return raw}
  function hideReportBadge(kind){setBadge(kind==='morning'?'morningReportBadge':kind==='evening'?'eveningReportBadge':'psychologyReportBadge',false)}
  async function copyText(text,button){const value=String(text||'');if(!value.trim())return;let copied=false;try{await navigator.clipboard.writeText(value);copied=true}catch(_){const area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{copied=document.execCommand('copy')}catch(__){}area.remove()}if(copied&&button){button.classList.add('is-copied');button.setAttribute('aria-label','Скопировано');setTimeout(()=>{button.classList.remove('is-copied');button.setAttribute('aria-label','Скопировать отчёт')},1200)}}
  function historyDateLabel(value){const parts=String(value||'').split('-').map(Number);if(parts.length!==3||!parts[0])return String(value||'');return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(new Date(parts[0],parts[1]-1,parts[2]))}
  function openHistoryModal(report){historyModalText=String(report.text||'');const morning=report.kind==='morning';$('reportHistoryModalKind').textContent=morning?'Утренний отчёт':'Вечерний отчёт';$('reportHistoryModalKind').className='report-history-kind '+(morning?'morning':'evening');$('reportHistoryModalTitle').textContent=historyDateLabel(report.reportDate);$('reportHistoryModalText').textContent=historyModalText;$('reportHistoryModal').classList.remove('hidden')}
  function renderReportHistory(reports){const list=$('reportHistoryList');list.innerHTML='';if(!reports.length){const empty=document.createElement('div');empty.className='report-history-empty';empty.textContent='Сохранённых отчётов пока нет.';list.appendChild(empty);return}reports.forEach((report,index)=>{const morning=report.kind==='morning',card=document.createElement('button');card.type='button';card.className='report-history-card report-history-card-enter '+(morning?'morning':'evening');card.style.setProperty('--report-history-delay',Math.min(index*34,238)+'ms');const kind=document.createElement('span');kind.className='report-history-card-kind';kind.textContent=morning?'☀️ Утренний отчёт':'🌙 Вечерний отчёт';const date=document.createElement('span');date.className='report-history-card-date';date.textContent=historyDateLabel(report.reportDate);const preview=document.createElement('span');preview.className='report-history-card-preview';preview.textContent=String(report.text||'').replace(/\s+/g,' ').trim();card.append(kind,date,preview);card.onclick=()=>openHistoryModal(report);list.appendChild(card)})}
  async function openReportHistory(){setHeader('История отчётов','Утренние и вечерние отчёты по дням.');$('reportHistoryError').classList.add('hidden');$('reportHistoryList').innerHTML='<div class="report-loading"><span class="report-loading-spinner"></span><span>Загружаем историю...</span></div>';show('screenReportHistory');try{const session=d1Session||await warmD1();if(!session||!session.token)throw new Error('Не удалось получить доступ к истории.');const response=await fetch('/lab/report-history',{headers:{'X-Medsi-Chat-Session':session.token},cache:'no-store'});const value=await response.json();if(!response.ok||!value.ok)throw new Error(value.message||'История временно недоступна.');renderReportHistory(Array.isArray(value.reports)?value.reports:[])}catch(e){$('reportHistoryList').innerHTML='';$('reportHistoryError').textContent=String(e&&e.message||e);$('reportHistoryError').classList.remove('hidden')}}
  async function openReport(kind){currentReportKind=kind;currentReportText='';setHeader(reportTitle(kind),'');const hasHistory=kind==='morning'||kind==='evening';$('reportDisclaimer').classList.toggle('hidden',kind==='psychology');$('reportCopyBtn').classList.add('hidden');$('reportHistoryBtn').classList.toggle('hidden',!hasHistory);$('reportContent').innerHTML='<div class="report-loading"><span class="report-loading-spinner"></span><span>Загружаем...</span></div>';$('reportError').classList.add('hidden');show('screenReport');hideReportBadge(kind);const cached=reportCache[kind]||null;const res=await warmReport(kind,true)||cached;if(!res||!res.ok){$('reportError').textContent=(res&&res.message)||'Отчёт пока недоступен.';$('reportError').classList.remove('hidden');$('reportContent').textContent='';return}currentReportText=dedupeExactReport(res.text||'Отчёта пока нет. Пожалуйста, попробуйте позже 🙏');$('reportContent').textContent=currentReportText;$('reportCopyBtn').classList.toggle('hidden',!currentReportText.trim())}
  function showSchedule(){setHeader('Режим дня','Расписание детского отделения.');show('screenSchedule')}
  async function openChat(){try{const session=d1Session||await warmD1();if(!session)throw new Error('Не удалось получить доступ к чату.');if(!window.MedsiParentChatScreen)throw new Error('Чат не загрузился.');setBadge('newMsgBanner',false);show('screenChat');await MedsiParentChatScreen.open({session,phone:currentPhone,parentName,childName,onBack:showChoose})}catch(e){alert(String(e&&e.message||e))}}

  $('btnGoRegister').onclick=()=>showNames();$('btnGoAuth').onclick=()=>showAuth();$('startHelpBtn').onclick=()=>{const p=$('startHelpPanel'),open=p.classList.toggle('is-open');p.setAttribute('aria-hidden',open?'false':'true')};
  $('namesBackBtn').onclick=showStart;$('namesAuthBtn').onclick=showAuth;$('phoneRegBackBtn').onclick=showNames;$('authBackBtn').onclick=showStart;
  $('toPhoneReg').onclick=()=>{const pFirst=$('parentFirst').value.trim(),pLast=$('parentLast').value.trim(),cFirst=$('childFirst').value.trim(),cLast=$('childLast').value.trim(),err=$('namesError');if(!pFirst||!cFirst){err.textContent='Введите имя родителя и имя ребёнка.';err.classList.remove('hidden');return}if(!cLast&&!pLast){err.textContent='Введите фамилию ребёнка или фамилию родителя.';err.classList.remove('hidden');return}if(![pFirst,pLast,cFirst,cLast].filter(Boolean).every(isSingleWord)){err.textContent='В каждое поле вводите только имя или фамилию, без отчества.';err.classList.remove('hidden');return}err.classList.add('hidden');regParentName=[pFirst,pLast].filter(Boolean).join(' ');regChildName=[cFirst,cLast].filter(Boolean).join(' ');showPhoneReg()};
  $('registerBtn').onclick=register;$('authBtn').onclick=auth;$('btnChat').onclick=openChat;$('btnMorning').onclick=()=>openReport('morning');$('btnEvening').onclick=()=>openReport('evening');$('btnPsychology').onclick=()=>openReport('psychology');$('btnSchedule').onclick=showSchedule;
  $('reportCopyBtn').onclick=()=>copyText(currentReportText,$('reportCopyBtn'));$('reportHistoryBtn').onclick=openReportHistory;$('historyBackBtn').onclick=()=>{setHeader(reportTitle(currentReportKind),'');show('screenReport')};$('reportHistoryModalCopy').onclick=()=>copyText(historyModalText,$('reportHistoryModalCopy'));$('reportHistoryModalClose').onclick=()=>$('reportHistoryModal').classList.add('hidden');$('reportHistoryModal').onclick=e=>{if(e.target===$('reportHistoryModal'))$('reportHistoryModal').classList.add('hidden')};
  $('authPendingBackBtn').onclick=()=>{flowRun++;safeRemove(REAUTH_KEY);showAuth()};
  ['reportBackBtn','scheduleBackBtn'].forEach(id=>$(id).onclick=showChoose);$('logoutBtn').onclick=()=>$('logoutModal').classList.remove('hidden');$('logoutCancelBtn').onclick=()=>$('logoutModal').classList.add('hidden');$('logoutConfirmBtn').onclick=()=>{$('logoutModal').classList.add('hidden');clearSession();safeRemove(REAUTH_KEY);justRegistered=false;showStart()};
  ['phoneInputReg','phoneInputAuth'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')(id==='phoneInputReg'?register:auth)()}));
  function boot(){initPush();const ph=onlyDigits(safeGet(PHONE_KEY)||safeGet(LEGACY_PHONE_KEY)),session=safeGet(PARENT_SESSION_KEY);if(validPhone(ph)&&session){restoreSaved();return}const reauth=readJson(REAUTH_KEY);if(reauth&&validPhone(reauth.phone)&&reauth.requestId){runReauthorizationFlow(reauth,false);return}const registration=readJson(REG_ATTEMPT_KEY);if(registration&&validPhone(registration.phone)&&registration.attemptId){runRegistrationFlow(registration);return}showStart()}
  boot();
})();
