(function(){
  const APP_BASE_URL='https://script.google.com/macros/s/AKfycbzRKRjjI7NoHx8rD5ifEdrcexGuYlMEB453sOC2UTZDeBaybZiNPIY0vDTMkmeHhebVpA/exec';
  const PUSH_SERVICE_URL='https://medsi-push-worker.medsi-children.workers.dev';
  const PHONE_KEY='medsi_parent_phone',LEGACY_PHONE_KEY='medsi_phone',PARENT_KEY='medsi_parent',CHILD_KEY='medsi_child',PARENT_SESSION_KEY='medsi_parent_auth_session_v1',D1_KEY='medsi_d1_parent_session_v1',REG_ATTEMPT_KEY='medsi_parent_registration_attempt_v1',REAUTH_KEY='medsi_parent_reauthorization_v1';
  const $=id=>document.getElementById(id);
  const reportCache={},reportPending={};let currentPhone='',parentName='',childName='',regParentName='',regChildName='',justRegistered=false,d1Session=null,pushReady=false,parentSession='',flowRun=0,currentReportKind='morning',currentReportText='',reportHistoryByDate={},reportHistoryMonth=0,reportHistoryMinMonth=0,reportHistoryMaxMonth=0,selectedHistoryDate='';
  const onlyDigits=v=>String(v||'').replace(/\D+/g,'');const validPhone=v=>onlyDigits(v).length>=10;
  const safeGet=k=>{try{return localStorage.getItem(k)||''}catch(_){return''}};
  const safeSet=(k,v)=>{try{localStorage.setItem(k,v)}catch(_){}};const safeRemove=k=>{try{localStorage.removeItem(k)}catch(_){}};
  function timeout(ms){return new Promise((_,reject)=>setTimeout(()=>reject(new Error('TIMEOUT')),ms))}
  async function callApi(method,args,ms){const run=async()=>{const r=await fetch(APP_BASE_URL,{method:'POST',headers:{'content-type':'text/plain;charset=UTF-8'},body:JSON.stringify({action:'api',method,args:args||[]}),cache:'no-store'});const raw=await r.text();let p;try{p=JSON.parse(raw)}catch(_){throw new Error('Apps Script вернул некорректный ответ.')}if(!r.ok||!p||p.ok!==true)throw new Error((p&&p.message)||('HTTP '+r.status));return p.result};return Promise.race([run(),timeout(ms||15000)])}
  function isStartLike(id){return id==='screenStart'||id==='screenChoose'}
  function initPush(){if(pushReady||!window.MedsiPush)return;pushReady=true;const ph=onlyDigits(safeGet(PHONE_KEY)||safeGet(LEGACY_PHONE_KEY));MedsiPush.init({frameId:'__no_parent_iframe__',appEndpointUrl:APP_BASE_URL,pushServiceUrl:PUSH_SERVICE_URL,identity:validPhone(ph)?{role:'parent',phone:ph}:null})}
  function syncPushIdentity(){if(!window.MedsiPush)return;if(validPhone(currentPhone))MedsiPush.setIdentity({role:'parent',phone:currentPhone,parentSession:parentSession||''});else MedsiPush.clearIdentity()}
  function show(id){['screenStart','screenNames','screenPhoneReg','screenAuth','screenRegistrationPending','screenAuthPending','screenChoose','screenReport','screenReportHistory','screenSchedule','screenChat'].forEach(x=>$(x).classList.toggle('hidden',x!==id));document.body.dataset.screen=id;$('appCard').classList.toggle('start-mode',id==='screenStart');$('headerBlock').classList.toggle('hidden',isStartLike(id)||id==='screenChat'||id==='screenRegistrationPending'||id==='screenAuthPending');const el=$(id);el.classList.remove('screen-enter');void el.offsetWidth;el.classList.add('screen-enter');setTimeout(()=>el.classList.remove('screen-enter'),300);setChips();if(window.MedsiPush)MedsiPush.setPanelVisible(id==='screenChoose'||id==='screenChat');window.scrollTo(0,0)}
  function setHeader(title,meta){$('title').textContent=title;$('meta').textContent=meta||''}
  function setChips(){const screen=document.body.dataset.screen||'',registrationPending=screen==='screenRegistrationPending',authPending=screen==='screenAuthPending',pendingVisible=registrationPending||authPending,authed=!!currentPhone&&!!parentSession&&!['screenStart','screenNames','screenPhoneReg','screenAuth','screenRegistrationPending','screenAuthPending'].some(id=>!$(id).classList.contains('hidden'));let displayChild=childName||'',displayPhone=currentPhone?('8'+onlyDigits(currentPhone).slice(-10)):'';if(registrationPending){const pending=readJson(REG_ATTEMPT_KEY)||{};displayChild=String(pending.childName||regChildName||'').trim();displayPhone=pending.phone?('8'+onlyDigits(pending.phone).slice(-10)):''}else if(authPending){const pending=readJson(REAUTH_KEY)||{};displayChild='';displayPhone=pending.phone?('8'+onlyDigits(pending.phone).slice(-10)):''}const chips=$('chips'),visible=authed||pendingVisible;chips.classList.toggle('hidden',!visible);chips.style.display=visible?'flex':'none';$('childChip').textContent=displayChild;$('childChip').classList.toggle('hidden',!displayChild);$('phoneChip').textContent=displayPhone;$('phoneChip').classList.toggle('hidden',!displayPhone);const logout=$('logoutBtn');if(logout){logout.textContent='Выйти';logout.classList.toggle('hidden',pendingVisible)}}
  function setBadge(id,visible){const el=$(id);if(!el)return;el.classList.toggle('hidden',!visible);requestAnimationFrame(()=>el.classList.toggle('show',!!visible))}
  function applyUnread(res){const unread=res&&res.reportUnread||{};setBadge('newMsgBanner',!!(res&&res.hasUnread));setBadge('morningReportBadge',!!unread.morning);setBadge('eveningReportBadge',!!unread.evening);setBadge('psychologyReportBadge',!!unread.psychology)}
  function showStart(){setHeader('Медси Бот','Облачная система для просмотра отчётов по вашему ребёнку и для связи с воспитателями.');show('screenStart')}
  function showNames(){setHeader('Регистрация родителя','Укажите данные ребёнка и родителя.');show('screenNames')}
  function showPhoneReg(){setHeader('Телефон для входа','Введите номер, с которым будете входить в систему.');show('screenPhoneReg')}
  function showAuth(){setHeader('Авторизация','Введите номер телефона, который вы указывали при регистрации.');show('screenAuth')}
  function applyBootstrap(res){if(!res||!res.ok||!res.parentSession)return false;currentPhone=onlyDigits(res.phone||currentPhone);parentName=String(res.parentName||parentName||'').trim();childName=String(res.childName||childName||'').trim();parentSession=String(res.parentSession);safeSet(PARENT_SESSION_KEY,parentSession);safeSet(PHONE_KEY,currentPhone);safeSet(LEGACY_PHONE_KEY,currentPhone);safeSet(PARENT_KEY,parentName);safeSet(CHILD_KEY,childName);applyUnread(res);syncPushIdentity();return true}
  function showChoose(){if(window.MedsiParentChatScreen)MedsiParentChatScreen.close();setHeader('Медси Бот','Облачная система для просмотра отчётов по вашему ребёнку и для связи с воспитателями.');$('waitNote').classList.toggle('hidden',!justRegistered);prewarmAll();show('screenChoose')}
  function clearSession(){currentPhone='';parentName='';childName='';parentSession='';d1Session=null;flowRun++;safeRemove(PHONE_KEY);safeRemove(LEGACY_PHONE_KEY);safeRemove(PARENT_KEY);safeRemove(CHILD_KEY);safeRemove(PARENT_SESSION_KEY);safeRemove(D1_KEY);Object.keys(reportCache).forEach(k=>delete reportCache[k]);Object.keys(reportPending).forEach(k=>delete reportPending[k]);if(window.MedsiParentPrewarm)MedsiParentPrewarm.clear();if(window.MedsiParentChatScreen)MedsiParentChatScreen.close();syncPushIdentity()}
  async function restoreSaved(){
    const ph=onlyDigits(safeGet(PHONE_KEY)||safeGet(LEGACY_PHONE_KEY));
    if(!validPhone(ph)){showStart();return}
    currentPhone=ph;
    parentName=String(safeGet(PARENT_KEY)||'').trim();
    childName=String(safeGet(CHILD_KEY)||'').trim();
    parentSession=safeGet(PARENT_SESSION_KEY);if(!parentSession){clearSession();$('phoneInputAuth').value=ph;showAuth();return}syncPushIdentity();
    showChoose();
    try{
      const res=await callApi('getParentBootstrap',[ph,parentSession],12000);
      if(!applyBootstrap(res)){clearSession();$('phoneInputAuth').value=ph;showAuth();return}
      setChips();
      prewarmAll();
    }catch(_){
      // A temporary network failure must not kick an already saved parent out.
      // The visible menu stays available and background prewarm can recover later.
    }
  }
  function isSingleWord(v){return !/\s/.test(String(v||'').trim())}
  const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  function readJson(key){try{return JSON.parse(safeGet(key)||'null')}catch(_){return null}}
  function makeFlowId(prefix){let value='';try{if(crypto&&crypto.randomUUID)value=crypto.randomUUID()}catch(_){}if(!value)value=Date.now().toString(36)+'_'+Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2);return prefix+'_'+value.replace(/[^A-Za-z0-9_-]/g,'')}
  function registrationFingerprint(data){return [onlyDigits(data.phone).slice(-10),data.parentName,data.childName].join('|')}
  function finishRegistration(res){if(!applyBootstrap(res))throw new Error('Регистрация завершена, но сессия не получена. Продолжаем проверку.');safeRemove(REG_ATTEMPT_KEY);justRegistered=true;showChoose();prewarmAll()}
  async function runRegistrationFlow(data){
    const run=++flowRun;
    show('screenRegistrationPending');
    const pendingText=$('registrationPendingText');
    pendingText.textContent='Пожалуйста, подождите. Мы сохраняем данные и готовим Медси Бот.';
    let phase='register',delay=1000,notFoundCount=0;
    while(run===flowRun){
      try{
        let res=null;
        if(phase==='register'){
          try{
            res=await callApi('registerParent',[data.parentName,data.childName,data.phone,data.attemptId],20000);
          }catch(_){
            if(run!==flowRun)return;
            phase='status';
            pendingText.textContent='Регистрация занимает больше времени, чем обычно. Проверяем результат…';
          }
          if(run!==flowRun)return;
          if(res){
            if(res.duplicate){safeRemove(REG_ATTEMPT_KEY);$('phoneInputAuth').value=data.phone;await beginReauthorization(data.phone);return}
            if(res.ok&&res.parentSession){finishRegistration(res);return}
            phase='status';
          }
        }
        if(phase==='status'){
          const statusRes=await callApi('getParentRegistrationStatus',[data.phone,data.attemptId],10000);
          if(run!==flowRun)return;
          if(statusRes&&statusRes.ok&&statusRes.parentSession){finishRegistration(statusRes);return}
          if(statusRes&&statusRes.result&&statusRes.result.parentSession){finishRegistration(statusRes.result);return}
          const status=String(statusRes&&(statusRes.status||statusRes.code)||'').toUpperCase();
          if(status==='NOT_FOUND'){
            notFoundCount++;
            if(notFoundCount>=3){phase='register';notFoundCount=0;pendingText.textContent='Проверяем регистрацию ещё раз…'}
          }else{
            notFoundCount=0;
            pendingText.textContent='Регистрация занимает больше времени, чем обычно. Проверяем результат…';
          }
        }
      }catch(_){
        if(run!==flowRun)return;
        phase='status';
        pendingText.textContent='Регистрация занимает больше времени, чем обычно. Проверяем результат…';
      }
      await wait(delay);
      delay=Math.min(3500,delay+400);
    }
  }
  async function register(){const digits=onlyDigits($('phoneInputReg').value),err=$('phoneErrorReg'),info=$('alreadyRegistered');err.classList.add('hidden');info.classList.add('hidden');if(!validPhone(digits)){err.textContent='Введите номер — минимум 10 цифр.';err.classList.remove('hidden');return}const snapshot={phone:digits,parentName:regParentName,childName:regChildName};const saved=readJson(REG_ATTEMPT_KEY);snapshot.attemptId=saved&&saved.fingerprint===registrationFingerprint(snapshot)?saved.attemptId:makeFlowId('reg');snapshot.fingerprint=registrationFingerprint(snapshot);safeSet(REG_ATTEMPT_KEY,JSON.stringify(snapshot));runRegistrationFlow(snapshot)}
  function resetAuthPendingUi(){const screen=$('screenAuthPending');screen.classList.remove('is-approved');$('authPendingSpinner').classList.remove('hidden');$('authApprovedIcon').classList.add('hidden');$('authPendingTitle').textContent='Авторизация начата';$('authPendingText').textContent='Пожалуйста, подождите, пока воспитатель подтвердит вход.';$('authRequestCodeWrap').classList.remove('hidden');$('authPendingBackBtn').classList.add('hidden')}
  function showAuthApproved(res){if(!applyBootstrap(res))throw new Error('Не удалось сохранить подтверждённый вход.');safeRemove(REAUTH_KEY);prewarmAll();const screen=$('screenAuthPending');screen.classList.add('is-approved');$('authPendingSpinner').classList.add('hidden');$('authApprovedIcon').classList.remove('hidden');$('authRequestCodeWrap').classList.add('hidden');$('authPendingTitle').textContent='Авторизация подтверждена!';$('authPendingText').textContent='Вход сохранён на этом устройстве.';setTimeout(()=>{if(document.body.dataset.screen==='screenAuthPending'){justRegistered=false;showChoose()}},1800)}
  function showAuthStopped(status,message){$('authPendingSpinner').classList.add('hidden');$('authRequestCodeWrap').classList.add('hidden');$('authPendingTitle').textContent=status==='DENIED'?'Авторизация отклонена':status==='NOT_FOUND'?'Номер не найден':'Срок запроса истёк';$('authPendingText').textContent=message||'Вы можете отправить новый запрос.';$('authPendingBackBtn').classList.remove('hidden')}
  async function runReauthorizationFlow(data,createFirst){const run=++flowRun;resetAuthPendingUi();show('screenAuthPending');let shouldCreate=!!createFirst;while(run===flowRun){try{const res=shouldCreate?await callApi('requestParentReauthorization',[data.phone,data.requestId],18000):await callApi('getParentReauthorizationStatus',[data.phone,data.requestId],12000);if(run!==flowRun)return;if(res&&res.code==='NOT_FOUND'&&res.ok===false){safeRemove(REAUTH_KEY);showAuthStopped('NOT_FOUND',res.message||'Этот номер не найден среди активных родителей.');return}shouldCreate=false;if(!res||res.ok===false)throw new Error((res&&res.message)||'Не удалось проверить авторизацию.');if(res.code)$('authRequestCode').textContent=res.code;if(res.parentSession||res.status==='APPROVED'){showAuthApproved(res);return}if(res.status==='DENIED'){safeRemove(REAUTH_KEY);showAuthStopped('DENIED','Воспитатель отклонил запрос. При необходимости свяжитесь с отделением.');return}if(res.status==='EXPIRED'){safeRemove(REAUTH_KEY);showAuthStopped('EXPIRED','Запрос больше не действует. Отправьте новый запрос на вход.');return}if(res.status==='NOT_FOUND')shouldCreate=true}catch(e){if(run!==flowRun)return;$('authPendingText').textContent='Связь временно прервана. Продолжаем проверять запрос…'}await wait(1500)}}
  async function beginReauthorization(phoneRaw){const digits=onlyDigits(phoneRaw);if(!validPhone(digits))return;let saved=readJson(REAUTH_KEY);if(!saved||onlyDigits(saved.phone).slice(-10)!==digits.slice(-10))saved={phone:digits,requestId:makeFlowId('auth')};safeSet(REAUTH_KEY,JSON.stringify(saved));runReauthorizationFlow(saved,true)}
  async function auth(){const digits=onlyDigits($('phoneInputAuth').value),err=$('phoneErrorAuth');err.classList.add('hidden');if(!validPhone(digits)){err.textContent='Введите номер — минимум 10 цифр.';err.classList.remove('hidden');return}beginReauthorization(digits)}
  function extractSession(res){if(res&&res.token)return res;if(res&&res.session&&res.session.token)return res.session;return null}
  function saveD1Session(session){if(!session||!session.token)return null;d1Session=session;safeSet(D1_KEY,JSON.stringify({phone:onlyDigits(currentPhone).slice(-10),session}));return session}
  async function warmD1(){if(!currentPhone)return null;try{const saved=JSON.parse(safeGet(D1_KEY)||'null');const s=extractSession(saved);const phone=onlyDigits(saved&&saved.phone||currentPhone).slice(-10);if(s&&Number(s.expiresAt||0)>Date.now()+30000&&phone===onlyDigits(currentPhone).slice(-10))return saveD1Session(s)}catch(_){}try{const res=await callApi('getD1ChatSession',['parent',currentPhone,parentSession],10000);const s=extractSession(res);return s?saveD1Session(s):null}catch(_){return null}}
  function normalizeCurrentReports(value){const reports={morning:{ok:true,text:'Отчёта пока нет. Пожалуйста, попробуйте позже 🙏',hasReport:false,version:'',updatedAt:0},evening:{ok:true,text:'Отчёта пока нет. Пожалуйста, попробуйте позже 🙏',hasReport:false,version:'',updatedAt:0},psychology:{ok:true,text:'Отчёта пока нет. Пожалуйста, попробуйте позже 🙏',hasReport:false,version:'',updatedAt:0}};(Array.isArray(value&&value.reports)?value.reports:[]).forEach(item=>{const kind=String(item&&item.kind||'').toLowerCase();if(!['morning','evening','psychology'].includes(kind))return;const text=String(item&&item.text||'').trim();reports[kind]={ok:true,text:text||'Отчёта пока нет. Пожалуйста, попробуйте позже 🙏',hasReport:!!text,version:String(item&&item.version||''),updatedAt:Number(item&&item.updatedAt||0)}});return reports}
  async function fetchCurrentReportsFromD1(session){if(!session||!session.token)throw new Error('D1 session is unavailable.');const response=await fetch('/lab/report-current',{headers:{'X-Medsi-Chat-Session':session.token},cache:'no-store'});const value=await response.json();if(!response.ok||!value.ok)throw new Error(value&&value.message||'Текущие отчёты временно недоступны.');return normalizeCurrentReports(value)}
  function warmAllReports(){const kinds=['morning','evening','psychology'];if(!currentPhone||kinds.every(kind=>reportCache[kind]||reportPending[kind]))return;const phone=currentPhone,session=parentSession;const sessionPromise=warmD1();sessionPromise.then(chatSession=>{if(chatSession&&window.MedsiParentPrewarm)MedsiParentPrewarm.warm(chatSession,currentPhone)});const batch=sessionPromise.then(fetchCurrentReportsFromD1).then(reports=>{if(onlyDigits(currentPhone).slice(-10)!==onlyDigits(phone).slice(-10)||parentSession!==session)return{};kinds.forEach(kind=>{if(reports[kind])reportCache[kind]=reports[kind]});return reports}).catch(()=>({}));kinds.forEach(kind=>{if(reportCache[kind]||reportPending[kind])return;const pending=batch.then(reports=>reports[kind]||null).finally(()=>{if(reportPending[kind]===pending)delete reportPending[kind]});reportPending[kind]=pending})}
  function warmReport(kind){if(reportPending[kind])return reportPending[kind];if(reportCache[kind])return Promise.resolve(reportCache[kind]);warmAllReports();return reportPending[kind]||Promise.resolve(null)}
  function prewarmAll(){if(!currentPhone)return;warmAllReports()}
  async function refreshParentMenu(){if(!currentPhone||!parentSession)return;const bootstrap=callApi('getParentBootstrap',[currentPhone,parentSession],12000).then(res=>{if(applyBootstrap(res))setChips()});const chat=warmD1().then(session=>session&&window.MedsiParentPrewarm?MedsiParentPrewarm.warm(session,currentPhone):null);await Promise.allSettled([bootstrap,chat])}
  function reportTitle(kind){return kind==='morning'?'Утренний отчёт':kind==='evening'?'Вечерний отчёт':'Групповая психотерапия'}
  function normalizeBlock(v){return String(v||'').replace(/\s+/g,' ').trim()}
  function dedupeExactReport(text){const raw=String(text||'').trim();if(!raw)return raw;const blocks=raw.split(/\n\s*\n+/).map(x=>x.trim()).filter(Boolean);if(blocks.length>1){const seen=new Set(),unique=[];for(const block of blocks){const key=normalizeBlock(block);if(!key||seen.has(key))continue;seen.add(key);unique.push(block)}if(unique.length<blocks.length)return unique.join('\n\n')}const lines=raw.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(lines.length===2&&normalizeBlock(lines[0])===normalizeBlock(lines[1]))return lines[0];return raw}
  function hideReportBadge(kind){setBadge(kind==='morning'?'morningReportBadge':kind==='evening'?'eveningReportBadge':'psychologyReportBadge',false)}
  function showReportResult(kind,res){if(document.body.dataset.screen!=='screenReport'||currentReportKind!==kind)return false;if(!res||!res.ok){$('reportError').textContent=(res&&res.message)||'Отчёт пока недоступен.';$('reportError').classList.remove('hidden');$('reportContent').textContent='';return false}$('reportError').classList.add('hidden');currentReportText=dedupeExactReport(res.text||'Отчёта пока нет. Пожалуйста, попробуйте позже 🙏');$('reportContent').textContent=currentReportText;$('reportCopyBtn').classList.toggle('hidden',!currentReportText.trim());return true}
  async function copyText(text,button){const value=String(text||'');if(!value.trim())return;let copied=false;try{await navigator.clipboard.writeText(value);copied=true}catch(_){const area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{copied=document.execCommand('copy')}catch(__){}area.remove()}if(copied&&button){button.classList.add('is-copied');button.setAttribute('aria-label','Скопировано');setTimeout(()=>{button.classList.remove('is-copied');button.setAttribute('aria-label','Скопировать отчёт')},1200)}}
  const historyCopyIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"></rect><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"></path></svg>';
  const historySunIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.5"></circle><path d="M12 2v2.2M12 19.8V22M2 12h2.2M19.8 12H22M4.9 4.9l1.6 1.6M17.5 17.5l1.6 1.6M19.1 4.9l-1.6 1.6M6.5 17.5l-1.6 1.6"></path></svg>';
  const historyMoonIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19.4 15.1A8.2 8.2 0 0 1 8.9 4.6 8.2 8.2 0 1 0 19.4 15.1Z"></path></svg>';
  function historyDateParts(value){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value||''));if(!match)return null;const year=Number(match[1]),month=Number(match[2])-1,day=Number(match[3]);if(month<0||month>11||day<1||day>new Date(year,month+1,0).getDate())return null;return{year,month,day}}
  function historyDateLabel(value){const parts=historyDateParts(value);if(!parts)return String(value||'');return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(new Date(parts.year,parts.month,parts.day))}
  function historyMonthLabel(year,month){const label=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(new Date(year,month,1)).replace(/\s*г\.$/,'');return label.charAt(0).toUpperCase()+label.slice(1)}
  function historyDateKey(year,month,day){return year+'-'+String(month+1).padStart(2,'0')+'-'+String(day).padStart(2,'0')}
  function closeHistoryModal(){$('reportHistoryModal').classList.add('hidden')}
  function makeHistoryReportSection(report){const morning=report.kind==='morning',section=document.createElement('section');section.className='report-history-day-report';const head=document.createElement('div');head.className='report-history-day-head';const label=document.createElement('div');label.className='report-history-day-kind';label.innerHTML=(morning?historySunIcon:historyMoonIcon)+'<span>'+(morning?'Утренний отчёт':'Вечерний отчёт')+'</span>';const copy=document.createElement('button');copy.type='button';copy.className='report-copy-btn';copy.setAttribute('aria-label','Скопировать отчёт');copy.title='Скопировать отчёт';copy.innerHTML=historyCopyIcon;const text=document.createElement('div');text.className='report-history-day-text';text.textContent=String(report.text||'');copy.onclick=()=>copyText(report.text||'',copy);head.append(label,copy);section.append(head,text);return section}
  function openHistoryDay(date){const reports=(reportHistoryByDate[date]||[]).slice().sort((a,b)=>a.kind==='morning'&&b.kind!=='morning'?-1:a.kind!=='morning'&&b.kind==='morning'?1:0);if(!reports.length)return;selectedHistoryDate=date;$('reportHistoryModalTitle').textContent=historyDateLabel(date);const body=$('reportHistoryModalReports');body.replaceChildren(...reports.map(makeHistoryReportSection));$('reportHistoryModal').classList.remove('hidden');renderReportCalendar()}
  function renderReportCalendar(){const list=$('reportHistoryList'),year=Math.floor(reportHistoryMonth/12),month=((reportHistoryMonth%12)+12)%12;list.innerHTML='';const calendar=document.createElement('div');calendar.className='report-calendar';const nav=document.createElement('div');nav.className='report-calendar-nav';const previous=document.createElement('button'),next=document.createElement('button'),title=document.createElement('div');previous.type=next.type='button';previous.className=next.className='report-calendar-arrow';previous.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6"></path></svg>';next.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg>';previous.setAttribute('aria-label','Предыдущий месяц');next.setAttribute('aria-label','Следующий месяц');previous.disabled=reportHistoryMonth<=reportHistoryMinMonth;next.disabled=reportHistoryMonth>=reportHistoryMaxMonth;previous.onclick=()=>{reportHistoryMonth--;selectedHistoryDate='';renderReportCalendar()};next.onclick=()=>{reportHistoryMonth++;selectedHistoryDate='';renderReportCalendar()};title.className='report-calendar-title';title.textContent=historyMonthLabel(year,month);nav.append(previous,title,next);const weekdays=document.createElement('div');weekdays.className='report-calendar-weekdays';['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].forEach(value=>{const day=document.createElement('span');day.textContent=value;weekdays.appendChild(day)});const grid=document.createElement('div');grid.className='report-calendar-grid';const offset=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate(),total=Math.ceil((offset+days)/7)*7;for(let index=0;index<total;index++){if(index<offset||index>=offset+days){const blank=document.createElement('span');blank.className='report-calendar-blank';grid.appendChild(blank);continue}const number=index-offset+1,key=historyDateKey(year,month,number),reports=reportHistoryByDate[key]||[],hasMorning=reports.some(report=>report.kind==='morning'),hasEvening=reports.some(report=>report.kind==='evening'),day=document.createElement('button');day.type='button';day.className='report-calendar-day'+(reports.length?' has-reports':'')+(selectedHistoryDate===key?' is-selected':'');day.disabled=!reports.length;day.setAttribute('aria-label',historyDateLabel(key)+(hasMorning&&hasEvening?', утренний и вечерний отчёты':hasMorning?', утренний отчёт':hasEvening?', вечерний отчёт':', отчётов нет'));const numberEl=document.createElement('span');numberEl.className='report-calendar-number';numberEl.textContent=String(number);const marks=document.createElement('span');marks.className='report-calendar-marks';if(hasMorning)marks.insertAdjacentHTML('beforeend',historySunIcon);if(hasEvening)marks.insertAdjacentHTML('beforeend',historyMoonIcon);day.append(numberEl,marks);if(reports.length)day.onclick=()=>openHistoryDay(key);grid.appendChild(day)}calendar.append(nav,weekdays,grid);list.appendChild(calendar)}
  function renderReportHistory(reports){const list=$('reportHistoryList'),valid=[];reportHistoryByDate={};selectedHistoryDate='';for(const report of reports){const parts=historyDateParts(report&&report.reportDate);if(!parts||!['morning','evening'].includes(report.kind))continue;const date=historyDateKey(parts.year,parts.month,parts.day);if(!reportHistoryByDate[date])reportHistoryByDate[date]=[];if(!reportHistoryByDate[date].some(item=>item.kind===report.kind))reportHistoryByDate[date].push(report);valid.push({date,month:parts.year*12+parts.month})}list.innerHTML='';if(!valid.length){const empty=document.createElement('div');empty.className='report-history-empty';empty.textContent='Сохранённых отчётов пока нет.';list.appendChild(empty);return}valid.sort((a,b)=>a.date.localeCompare(b.date));reportHistoryMinMonth=Math.min(...valid.map(item=>item.month));reportHistoryMaxMonth=Math.max(...valid.map(item=>item.month));reportHistoryMonth=reportHistoryMaxMonth;renderReportCalendar()}
  async function openReportHistory(){setHeader('История отчётов','Утренние и вечерние отчёты по дням.');$('reportHistoryError').classList.add('hidden');$('reportHistoryList').innerHTML='<div class="report-loading"><span class="report-loading-spinner"></span><span>Загружаем историю...</span></div>';show('screenReportHistory');try{const session=d1Session||await warmD1();if(!session||!session.token)throw new Error('Не удалось получить доступ к истории.');const response=await fetch('/lab/report-history',{headers:{'X-Medsi-Chat-Session':session.token},cache:'no-store'});const value=await response.json();if(!response.ok||!value.ok)throw new Error(value.message||'История временно недоступна.');renderReportHistory(Array.isArray(value.reports)?value.reports:[])}catch(e){$('reportHistoryList').innerHTML='';$('reportHistoryError').textContent=String(e&&e.message||e);$('reportHistoryError').classList.remove('hidden')}}
  async function openReport(kind){currentReportKind=kind;currentReportText='';setHeader(reportTitle(kind),'');const hasHistory=kind==='morning'||kind==='evening';$('reportDisclaimer').classList.toggle('hidden',kind==='psychology');$('reportCopyBtn').classList.add('hidden');$('reportHistoryBtn').classList.toggle('hidden',!hasHistory);$('reportContent').innerHTML='<div class="report-loading"><span class="report-loading-spinner"></span><span>Загружаем...</span></div>';$('reportError').classList.add('hidden');show('screenReport');hideReportBadge(kind);const cached=reportCache[kind]||null;if(cached&&cached.ok){showReportResult(kind,cached);return}const pending=warmReport(kind);const res=await Promise.race([pending,wait(12000).then(()=>null)]);if(showReportResult(kind,res))return;pending.then(late=>{if(late&&late.ok)showReportResult(kind,late)})}
  function showSchedule(){setHeader('Режим дня','Расписание детского отделения.');show('screenSchedule')}
  async function openChat(){try{const session=d1Session||await warmD1();if(!session)throw new Error('Не удалось получить доступ к чату.');if(!window.MedsiParentChatScreen)throw new Error('Чат не загрузился.');setBadge('newMsgBanner',false);show('screenChat');await MedsiParentChatScreen.open({session,phone:currentPhone,parentName,childName,onBack:showChoose})}catch(e){alert(String(e&&e.message||e))}}

  $('btnGoRegister').onclick=()=>showNames();$('btnGoAuth').onclick=()=>showAuth();$('startHelpBtn').onclick=()=>{const p=$('startHelpPanel'),open=p.classList.toggle('is-open');p.setAttribute('aria-hidden',open?'false':'true')};
  $('namesBackBtn').onclick=showStart;$('namesAuthBtn').onclick=showAuth;$('phoneRegBackBtn').onclick=showNames;$('authBackBtn').onclick=showStart;
  $('toPhoneReg').onclick=()=>{const pFirst=$('parentFirst').value.trim(),pLast=$('parentLast').value.trim(),cFirst=$('childFirst').value.trim(),cLast=$('childLast').value.trim(),err=$('namesError');if(!pFirst||!cFirst){err.textContent='Введите имя родителя и имя ребёнка.';err.classList.remove('hidden');return}if(!cLast&&!pLast){err.textContent='Введите фамилию ребёнка или фамилию родителя.';err.classList.remove('hidden');return}if(![pFirst,pLast,cFirst,cLast].filter(Boolean).every(isSingleWord)){err.textContent='В каждое поле вводите только имя или фамилию, без отчества.';err.classList.remove('hidden');return}err.classList.add('hidden');regParentName=[pFirst,pLast].filter(Boolean).join(' ');regChildName=[cFirst,cLast].filter(Boolean).join(' ');showPhoneReg()};
  $('registerBtn').onclick=register;$('authBtn').onclick=auth;$('btnChat').onclick=openChat;$('btnMorning').onclick=()=>openReport('morning');$('btnEvening').onclick=()=>openReport('evening');$('btnPsychology').onclick=()=>openReport('psychology');$('btnSchedule').onclick=showSchedule;
  $('reportCopyBtn').onclick=()=>copyText(currentReportText,$('reportCopyBtn'));$('reportHistoryBtn').onclick=openReportHistory;$('historyBackBtn').onclick=()=>{setHeader(reportTitle(currentReportKind),'');show('screenReport')};$('reportHistoryModalClose').onclick=closeHistoryModal;$('reportHistoryModal').onclick=e=>{if(e.target===$('reportHistoryModal'))closeHistoryModal()};
  $('authPendingBackBtn').onclick=()=>{flowRun++;safeRemove(REAUTH_KEY);showAuth()};
  ['reportBackBtn','scheduleBackBtn'].forEach(id=>$(id).onclick=showChoose);$('logoutBtn').onclick=()=>$('logoutModal').classList.remove('hidden');$('logoutCancelBtn').onclick=()=>$('logoutModal').classList.add('hidden');$('logoutConfirmBtn').onclick=()=>{$('logoutModal').classList.add('hidden');clearSession();safeRemove(REAUTH_KEY);justRegistered=false;showStart()};
  ['phoneInputReg','phoneInputAuth'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')(id==='phoneInputReg'?register:auth)()}));
  function installPullRefresh(){if(!window.MedsiPullToRefresh)return;MedsiPullToRefresh.register({id:'parent-menu',isActive:()=>document.body.dataset.screen==='screenChoose'&&!!parentSession&&$('logoutModal').classList.contains('hidden'),getScroller:()=>window,onRefresh:refreshParentMenu})}
  function boot(){installPullRefresh();initPush();const ph=onlyDigits(safeGet(PHONE_KEY)||safeGet(LEGACY_PHONE_KEY)),session=safeGet(PARENT_SESSION_KEY);if(validPhone(ph)&&session){restoreSaved();return}const reauth=readJson(REAUTH_KEY);if(reauth&&validPhone(reauth.phone)&&reauth.requestId){runReauthorizationFlow(reauth,false);return}const registration=readJson(REG_ATTEMPT_KEY);if(registration&&validPhone(registration.phone)&&registration.attemptId){runRegistrationFlow(registration);return}showStart()}
  boot();
})();
